CREATE DATABASE IF NOT EXISTS `ran-feed` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `xxl_job` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'ran_feed'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON `ran-feed`.* TO 'ran_feed'@'%';
GRANT ALL PRIVILEGES ON `xxl_job`.* TO 'ran_feed'@'%';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'ran_feed'@'%';
FLUSH PRIVILEGES;
