// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AdminInfo struct {
	AdminId  int64  `json:"admin_id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Status   int32  `json:"status"`
}

type AdminLoginReq struct {
	Username *string `json:"username,optional" validate:"required,max=64"`
	Password *string `json:"password,optional" validate:"required"`
}

type AdminLoginRes struct {
	AdminId     int64    `json:"admin_id"`
	Token       string   `json:"token"`
	ExpiredAt   int64    `json:"expired_at"`
	Nickname    string   `json:"nickname"`
	Permissions []string `json:"permissions"`
}

type AdminLogoutRes struct {
}

type AdminMeRes struct {
	AdminInfo   AdminInfo `json:"admin_info"`
	Permissions []string  `json:"permissions"`
}
