// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: admin.proto

package adminuserservice

import (
	"context"

	"ran-feed/app/rpc/admin/admin"

	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminListItem         = admin.AdminListItem
	CreateAdminReq        = admin.CreateAdminReq
	CreateAdminRes        = admin.CreateAdminRes
	GetAdminDetailReq     = admin.GetAdminDetailReq
	GetAdminDetailRes     = admin.GetAdminDetailRes
	ListAdminsReq         = admin.ListAdminsReq
	ListAdminsRes         = admin.ListAdminsRes
	ResetAdminPasswordReq = admin.ResetAdminPasswordReq
	SetAdminRolesReq      = admin.SetAdminRolesReq
	SetAdminStatusReq     = admin.SetAdminStatusReq
	UpdateAdminReq        = admin.UpdateAdminReq

	AdminUserService interface {
		ListAdmins(ctx context.Context, in *ListAdminsReq, opts ...grpc.CallOption) (*ListAdminsRes, error)
		GetAdminDetail(ctx context.Context, in *GetAdminDetailReq, opts ...grpc.CallOption) (*GetAdminDetailRes, error)
		CreateAdmin(ctx context.Context, in *CreateAdminReq, opts ...grpc.CallOption) (*CreateAdminRes, error)
		UpdateAdmin(ctx context.Context, in *UpdateAdminReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
		SetAdminStatus(ctx context.Context, in *SetAdminStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
		ResetAdminPassword(ctx context.Context, in *ResetAdminPasswordReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
		SetAdminRoles(ctx context.Context, in *SetAdminRolesReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	}

	defaultAdminUserService struct {
		cli zrpc.Client
	}
)

func NewAdminUserService(cli zrpc.Client) AdminUserService {
	return &defaultAdminUserService{
		cli: cli,
	}
}

func (m *defaultAdminUserService) ListAdmins(ctx context.Context, in *ListAdminsReq, opts ...grpc.CallOption) (*ListAdminsRes, error) {
	client := admin.NewAdminUserServiceClient(m.cli.Conn())
	return client.ListAdmins(ctx, in, opts...)
}

func (m *defaultAdminUserService) GetAdminDetail(ctx context.Context, in *GetAdminDetailReq, opts ...grpc.CallOption) (*GetAdminDetailRes, error) {
	client := admin.NewAdminUserServiceClient(m.cli.Conn())
	return client.GetAdminDetail(ctx, in, opts...)
}

func (m *defaultAdminUserService) CreateAdmin(ctx context.Context, in *CreateAdminReq, opts ...grpc.CallOption) (*CreateAdminRes, error) {
	client := admin.NewAdminUserServiceClient(m.cli.Conn())
	return client.CreateAdmin(ctx, in, opts...)
}

func (m *defaultAdminUserService) UpdateAdmin(ctx context.Context, in *UpdateAdminReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := admin.NewAdminUserServiceClient(m.cli.Conn())
	return client.UpdateAdmin(ctx, in, opts...)
}

func (m *defaultAdminUserService) SetAdminStatus(ctx context.Context, in *SetAdminStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := admin.NewAdminUserServiceClient(m.cli.Conn())
	return client.SetAdminStatus(ctx, in, opts...)
}

func (m *defaultAdminUserService) ResetAdminPassword(ctx context.Context, in *ResetAdminPasswordReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := admin.NewAdminUserServiceClient(m.cli.Conn())
	return client.ResetAdminPassword(ctx, in, opts...)
}

func (m *defaultAdminUserService) SetAdminRoles(ctx context.Context, in *SetAdminRolesReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := admin.NewAdminUserServiceClient(m.cli.Conn())
	return client.SetAdminRoles(ctx, in, opts...)
}
