// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: content.proto

package server

import (
	"context"

	"ran-feed/app/rpc/content/content"
	"ran-feed/app/rpc/content/internal/logic/admincontentservice"
	"ran-feed/app/rpc/content/internal/svc"
)

type AdminContentServiceServer struct {
	svcCtx *svc.ServiceContext
	content.UnimplementedAdminContentServiceServer
}

func NewAdminContentServiceServer(svcCtx *svc.ServiceContext) *AdminContentServiceServer {
	return &AdminContentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminContentServiceServer) AdminListContents(ctx context.Context, in *content.AdminListContentsReq) (*content.AdminListContentsRes, error) {
	l := admincontentservicelogic.NewAdminListContentsLogic(ctx, s.svcCtx)
	return l.AdminListContents(in)
}

func (s *AdminContentServiceServer) AdminGetContentDetail(ctx context.Context, in *content.AdminGetContentDetailReq) (*content.AdminGetContentDetailRes, error) {
	l := admincontentservicelogic.NewAdminGetContentDetailLogic(ctx, s.svcCtx)
	return l.AdminGetContentDetail(in)
}

func (s *AdminContentServiceServer) AdminSetContentStatus(ctx context.Context, in *content.AdminSetContentStatusReq) (*content.AdminSetContentStatusRes, error) {
	l := admincontentservicelogic.NewAdminSetContentStatusLogic(ctx, s.svcCtx)
	return l.AdminSetContentStatus(in)
}

func (s *AdminContentServiceServer) AdminReviewContent(ctx context.Context, in *content.AdminReviewContentReq) (*content.AdminReviewContentRes, error) {
	l := admincontentservicelogic.NewAdminReviewContentLogic(ctx, s.svcCtx)
	return l.AdminReviewContent(in)
}
