// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package adminpermissionservice

import (
	"context"

	"ran-feed/app/rpc/admin/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ListPermissionsReq = admin.ListPermissionsReq
	ListPermissionsRes = admin.ListPermissionsRes

	AdminPermissionService interface {
		ListPermissions(ctx context.Context, in *ListPermissionsReq, opts ...grpc.CallOption) (*ListPermissionsRes, error)
	}

	defaultAdminPermissionService struct {
		cli zrpc.Client
	}
)

func NewAdminPermissionService(cli zrpc.Client) AdminPermissionService {
	return &defaultAdminPermissionService{
		cli: cli,
	}
}

func (m *defaultAdminPermissionService) ListPermissions(ctx context.Context, in *ListPermissionsReq, opts ...grpc.CallOption) (*ListPermissionsRes, error) {
	client := admin.NewAdminPermissionServiceClient(m.cli.Conn())
	return client.ListPermissions(ctx, in, opts...)
}
