// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: search.proto

package searchservice

import (
	"context"

	"ran-feed/app/rpc/search/search"

	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ContentHit       = search.ContentHit
	DeleteHistoryReq = search.DeleteHistoryReq
	HistoryItem      = search.HistoryItem
	ListHistoryReq   = search.ListHistoryReq
	ListHistoryRes   = search.ListHistoryRes
	RecordHistoryReq = search.RecordHistoryReq
	SearchContentReq = search.SearchContentReq
	SearchContentRes = search.SearchContentRes
	SearchUserReq    = search.SearchUserReq
	SearchUserRes    = search.SearchUserRes
	SuggestItem      = search.SuggestItem
	SuggestReq       = search.SuggestReq
	SuggestRes       = search.SuggestRes
	UserHit          = search.UserHit

	SearchService interface {
		SearchContent(ctx context.Context, in *SearchContentReq, opts ...grpc.CallOption) (*SearchContentRes, error)
		SearchUser(ctx context.Context, in *SearchUserReq, opts ...grpc.CallOption) (*SearchUserRes, error)
		Suggest(ctx context.Context, in *SuggestReq, opts ...grpc.CallOption) (*SuggestRes, error)
		RecordHistory(ctx context.Context, in *RecordHistoryReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
		ListHistory(ctx context.Context, in *ListHistoryReq, opts ...grpc.CallOption) (*ListHistoryRes, error)
		DeleteHistory(ctx context.Context, in *DeleteHistoryReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	}

	defaultSearchService struct {
		cli zrpc.Client
	}
)

func NewSearchService(cli zrpc.Client) SearchService {
	return &defaultSearchService{
		cli: cli,
	}
}

func (m *defaultSearchService) SearchContent(ctx context.Context, in *SearchContentReq, opts ...grpc.CallOption) (*SearchContentRes, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.SearchContent(ctx, in, opts...)
}

func (m *defaultSearchService) SearchUser(ctx context.Context, in *SearchUserReq, opts ...grpc.CallOption) (*SearchUserRes, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.SearchUser(ctx, in, opts...)
}

func (m *defaultSearchService) Suggest(ctx context.Context, in *SuggestReq, opts ...grpc.CallOption) (*SuggestRes, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.Suggest(ctx, in, opts...)
}

func (m *defaultSearchService) RecordHistory(ctx context.Context, in *RecordHistoryReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.RecordHistory(ctx, in, opts...)
}

func (m *defaultSearchService) ListHistory(ctx context.Context, in *ListHistoryReq, opts ...grpc.CallOption) (*ListHistoryRes, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.ListHistory(ctx, in, opts...)
}

func (m *defaultSearchService) DeleteHistory(ctx context.Context, in *DeleteHistoryReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.DeleteHistory(ctx, in, opts...)
}
