// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ran-feed/app/rpc/admin/internal/entity/model"
)

func newRanFeedAdminUser(db *gorm.DB, opts ...gen.DOOption) ranFeedAdminUser {
	_ranFeedAdminUser := ranFeedAdminUser{}

	_ranFeedAdminUser.ranFeedAdminUserDo.UseDB(db, opts...)
	_ranFeedAdminUser.ranFeedAdminUserDo.UseModel(&model.RanFeedAdminUser{})

	tableName := _ranFeedAdminUser.ranFeedAdminUserDo.TableName()
	_ranFeedAdminUser.ALL = field.NewAsterisk(tableName)
	_ranFeedAdminUser.ID = field.NewInt64(tableName, "id")
	_ranFeedAdminUser.Username = field.NewString(tableName, "username")
	_ranFeedAdminUser.PasswordHash = field.NewString(tableName, "password_hash")
	_ranFeedAdminUser.Nickname = field.NewString(tableName, "nickname")
	_ranFeedAdminUser.Status = field.NewInt32(tableName, "status")
	_ranFeedAdminUser.Version = field.NewInt32(tableName, "version")
	_ranFeedAdminUser.IsDeleted = field.NewInt32(tableName, "is_deleted")
	_ranFeedAdminUser.CreatedBy = field.NewInt64(tableName, "created_by")
	_ranFeedAdminUser.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_ranFeedAdminUser.CreatedAt = field.NewTime(tableName, "created_at")
	_ranFeedAdminUser.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ranFeedAdminUser.fillFieldMap()

	return _ranFeedAdminUser
}

// ranFeedAdminUser 后台管理员账号表
type ranFeedAdminUser struct {
	ranFeedAdminUserDo ranFeedAdminUserDo

	ALL          field.Asterisk
	ID           field.Int64  // 管理员ID
	Username     field.String // 登录用户名唯一
	PasswordHash field.String // 密码哈希
	Nickname     field.String // 昵称
	Status       field.Int32  // 状态 10=启用 20=禁用
	Version      field.Int32  // 版本号（乐观锁）
	IsDeleted    field.Int32  // 逻辑删除 0=正常 1=删除
	CreatedBy    field.Int64  // 创建人
	UpdatedBy    field.Int64  // 最后修改人
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (r ranFeedAdminUser) Table(newTableName string) *ranFeedAdminUser {
	r.ranFeedAdminUserDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r ranFeedAdminUser) As(alias string) *ranFeedAdminUser {
	r.ranFeedAdminUserDo.DO = *(r.ranFeedAdminUserDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *ranFeedAdminUser) updateTableName(table string) *ranFeedAdminUser {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.Username = field.NewString(table, "username")
	r.PasswordHash = field.NewString(table, "password_hash")
	r.Nickname = field.NewString(table, "nickname")
	r.Status = field.NewInt32(table, "status")
	r.Version = field.NewInt32(table, "version")
	r.IsDeleted = field.NewInt32(table, "is_deleted")
	r.CreatedBy = field.NewInt64(table, "created_by")
	r.UpdatedBy = field.NewInt64(table, "updated_by")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *ranFeedAdminUser) WithContext(ctx context.Context) IRanFeedAdminUserDo {
	return r.ranFeedAdminUserDo.WithContext(ctx)
}

func (r ranFeedAdminUser) TableName() string { return r.ranFeedAdminUserDo.TableName() }

func (r ranFeedAdminUser) Alias() string { return r.ranFeedAdminUserDo.Alias() }

func (r ranFeedAdminUser) Columns(cols ...field.Expr) gen.Columns {
	return r.ranFeedAdminUserDo.Columns(cols...)
}

func (r *ranFeedAdminUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *ranFeedAdminUser) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 11)
	r.fieldMap["id"] = r.ID
	r.fieldMap["username"] = r.Username
	r.fieldMap["password_hash"] = r.PasswordHash
	r.fieldMap["nickname"] = r.Nickname
	r.fieldMap["status"] = r.Status
	r.fieldMap["version"] = r.Version
	r.fieldMap["is_deleted"] = r.IsDeleted
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["updated_by"] = r.UpdatedBy
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r ranFeedAdminUser) clone(db *gorm.DB) ranFeedAdminUser {
	r.ranFeedAdminUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r ranFeedAdminUser) replaceDB(db *gorm.DB) ranFeedAdminUser {
	r.ranFeedAdminUserDo.ReplaceDB(db)
	return r
}

type ranFeedAdminUserDo struct{ gen.DO }

type IRanFeedAdminUserDo interface {
	gen.SubQuery
	Debug() IRanFeedAdminUserDo
	WithContext(ctx context.Context) IRanFeedAdminUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRanFeedAdminUserDo
	WriteDB() IRanFeedAdminUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRanFeedAdminUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRanFeedAdminUserDo
	Not(conds ...gen.Condition) IRanFeedAdminUserDo
	Or(conds ...gen.Condition) IRanFeedAdminUserDo
	Select(conds ...field.Expr) IRanFeedAdminUserDo
	Where(conds ...gen.Condition) IRanFeedAdminUserDo
	Order(conds ...field.Expr) IRanFeedAdminUserDo
	Distinct(cols ...field.Expr) IRanFeedAdminUserDo
	Omit(cols ...field.Expr) IRanFeedAdminUserDo
	Join(table schema.Tabler, on ...field.Expr) IRanFeedAdminUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedAdminUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedAdminUserDo
	Group(cols ...field.Expr) IRanFeedAdminUserDo
	Having(conds ...gen.Condition) IRanFeedAdminUserDo
	Limit(limit int) IRanFeedAdminUserDo
	Offset(offset int) IRanFeedAdminUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedAdminUserDo
	Unscoped() IRanFeedAdminUserDo
	Create(values ...*model.RanFeedAdminUser) error
	CreateInBatches(values []*model.RanFeedAdminUser, batchSize int) error
	Save(values ...*model.RanFeedAdminUser) error
	First() (*model.RanFeedAdminUser, error)
	Take() (*model.RanFeedAdminUser, error)
	Last() (*model.RanFeedAdminUser, error)
	Find() ([]*model.RanFeedAdminUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedAdminUser, err error)
	FindInBatches(result *[]*model.RanFeedAdminUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RanFeedAdminUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRanFeedAdminUserDo
	Assign(attrs ...field.AssignExpr) IRanFeedAdminUserDo
	Joins(fields ...field.RelationField) IRanFeedAdminUserDo
	Preload(fields ...field.RelationField) IRanFeedAdminUserDo
	FirstOrInit() (*model.RanFeedAdminUser, error)
	FirstOrCreate() (*model.RanFeedAdminUser, error)
	FindByPage(offset int, limit int) (result []*model.RanFeedAdminUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRanFeedAdminUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r ranFeedAdminUserDo) Debug() IRanFeedAdminUserDo {
	return r.withDO(r.DO.Debug())
}

func (r ranFeedAdminUserDo) WithContext(ctx context.Context) IRanFeedAdminUserDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r ranFeedAdminUserDo) ReadDB() IRanFeedAdminUserDo {
	return r.Clauses(dbresolver.Read)
}

func (r ranFeedAdminUserDo) WriteDB() IRanFeedAdminUserDo {
	return r.Clauses(dbresolver.Write)
}

func (r ranFeedAdminUserDo) Session(config *gorm.Session) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Session(config))
}

func (r ranFeedAdminUserDo) Clauses(conds ...clause.Expression) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r ranFeedAdminUserDo) Returning(value interface{}, columns ...string) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r ranFeedAdminUserDo) Not(conds ...gen.Condition) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r ranFeedAdminUserDo) Or(conds ...gen.Condition) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r ranFeedAdminUserDo) Select(conds ...field.Expr) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r ranFeedAdminUserDo) Where(conds ...gen.Condition) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r ranFeedAdminUserDo) Order(conds ...field.Expr) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r ranFeedAdminUserDo) Distinct(cols ...field.Expr) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r ranFeedAdminUserDo) Omit(cols ...field.Expr) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r ranFeedAdminUserDo) Join(table schema.Tabler, on ...field.Expr) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r ranFeedAdminUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedAdminUserDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r ranFeedAdminUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedAdminUserDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r ranFeedAdminUserDo) Group(cols ...field.Expr) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r ranFeedAdminUserDo) Having(conds ...gen.Condition) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r ranFeedAdminUserDo) Limit(limit int) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r ranFeedAdminUserDo) Offset(offset int) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r ranFeedAdminUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r ranFeedAdminUserDo) Unscoped() IRanFeedAdminUserDo {
	return r.withDO(r.DO.Unscoped())
}

func (r ranFeedAdminUserDo) Create(values ...*model.RanFeedAdminUser) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r ranFeedAdminUserDo) CreateInBatches(values []*model.RanFeedAdminUser, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r ranFeedAdminUserDo) Save(values ...*model.RanFeedAdminUser) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r ranFeedAdminUserDo) First() (*model.RanFeedAdminUser, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedAdminUser), nil
	}
}

func (r ranFeedAdminUserDo) Take() (*model.RanFeedAdminUser, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedAdminUser), nil
	}
}

func (r ranFeedAdminUserDo) Last() (*model.RanFeedAdminUser, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedAdminUser), nil
	}
}

func (r ranFeedAdminUserDo) Find() ([]*model.RanFeedAdminUser, error) {
	result, err := r.DO.Find()
	return result.([]*model.RanFeedAdminUser), err
}

func (r ranFeedAdminUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedAdminUser, err error) {
	buf := make([]*model.RanFeedAdminUser, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r ranFeedAdminUserDo) FindInBatches(result *[]*model.RanFeedAdminUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r ranFeedAdminUserDo) Attrs(attrs ...field.AssignExpr) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r ranFeedAdminUserDo) Assign(attrs ...field.AssignExpr) IRanFeedAdminUserDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r ranFeedAdminUserDo) Joins(fields ...field.RelationField) IRanFeedAdminUserDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r ranFeedAdminUserDo) Preload(fields ...field.RelationField) IRanFeedAdminUserDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r ranFeedAdminUserDo) FirstOrInit() (*model.RanFeedAdminUser, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedAdminUser), nil
	}
}

func (r ranFeedAdminUserDo) FirstOrCreate() (*model.RanFeedAdminUser, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedAdminUser), nil
	}
}

func (r ranFeedAdminUserDo) FindByPage(offset int, limit int) (result []*model.RanFeedAdminUser, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r ranFeedAdminUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r ranFeedAdminUserDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r ranFeedAdminUserDo) Delete(models ...*model.RanFeedAdminUser) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *ranFeedAdminUserDo) withDO(do gen.Dao) *ranFeedAdminUserDo {
	r.DO = *do.(*gen.DO)
	return r
}
