// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ran-feed/app/rpc/admin/internal/entity/model"
)

func newRanFeedOperationLog(db *gorm.DB, opts ...gen.DOOption) ranFeedOperationLog {
	_ranFeedOperationLog := ranFeedOperationLog{}

	_ranFeedOperationLog.ranFeedOperationLogDo.UseDB(db, opts...)
	_ranFeedOperationLog.ranFeedOperationLogDo.UseModel(&model.RanFeedOperationLog{})

	tableName := _ranFeedOperationLog.ranFeedOperationLogDo.TableName()
	_ranFeedOperationLog.ALL = field.NewAsterisk(tableName)
	_ranFeedOperationLog.ID = field.NewInt64(tableName, "id")
	_ranFeedOperationLog.AdminID = field.NewInt64(tableName, "admin_id")
	_ranFeedOperationLog.Action = field.NewString(tableName, "action")
	_ranFeedOperationLog.TargetType = field.NewString(tableName, "target_type")
	_ranFeedOperationLog.TargetID = field.NewInt64(tableName, "target_id")
	_ranFeedOperationLog.Payload = field.NewString(tableName, "payload")
	_ranFeedOperationLog.Result = field.NewString(tableName, "result")
	_ranFeedOperationLog.IP = field.NewString(tableName, "ip")
	_ranFeedOperationLog.Version = field.NewInt32(tableName, "version")
	_ranFeedOperationLog.IsDeleted = field.NewInt32(tableName, "is_deleted")
	_ranFeedOperationLog.CreatedBy = field.NewInt64(tableName, "created_by")
	_ranFeedOperationLog.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_ranFeedOperationLog.CreatedAt = field.NewTime(tableName, "created_at")
	_ranFeedOperationLog.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ranFeedOperationLog.fillFieldMap()

	return _ranFeedOperationLog
}

// ranFeedOperationLog 后台操作审计日志表
type ranFeedOperationLog struct {
	ranFeedOperationLogDo ranFeedOperationLogDo

	ALL        field.Asterisk
	ID         field.Int64  // 日志ID
	AdminID    field.Int64  // 操作人管理员ID
	Action     field.String // 操作动作 如 content:takedown
	TargetType field.String // 目标类型 如 content/user
	TargetID   field.Int64  // 目标ID
	Payload    field.String // 入参摘要 JSON
	Result     field.String // 操作结果
	IP         field.String // 来源IP
	Version    field.Int32  // 版本号（乐观锁）
	IsDeleted  field.Int32  // 逻辑删除 0=正常 1=删除
	CreatedBy  field.Int64  // 创建人
	UpdatedBy  field.Int64  // 最后修改人
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (r ranFeedOperationLog) Table(newTableName string) *ranFeedOperationLog {
	r.ranFeedOperationLogDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r ranFeedOperationLog) As(alias string) *ranFeedOperationLog {
	r.ranFeedOperationLogDo.DO = *(r.ranFeedOperationLogDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *ranFeedOperationLog) updateTableName(table string) *ranFeedOperationLog {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.AdminID = field.NewInt64(table, "admin_id")
	r.Action = field.NewString(table, "action")
	r.TargetType = field.NewString(table, "target_type")
	r.TargetID = field.NewInt64(table, "target_id")
	r.Payload = field.NewString(table, "payload")
	r.Result = field.NewString(table, "result")
	r.IP = field.NewString(table, "ip")
	r.Version = field.NewInt32(table, "version")
	r.IsDeleted = field.NewInt32(table, "is_deleted")
	r.CreatedBy = field.NewInt64(table, "created_by")
	r.UpdatedBy = field.NewInt64(table, "updated_by")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *ranFeedOperationLog) WithContext(ctx context.Context) IRanFeedOperationLogDo {
	return r.ranFeedOperationLogDo.WithContext(ctx)
}

func (r ranFeedOperationLog) TableName() string { return r.ranFeedOperationLogDo.TableName() }

func (r ranFeedOperationLog) Alias() string { return r.ranFeedOperationLogDo.Alias() }

func (r ranFeedOperationLog) Columns(cols ...field.Expr) gen.Columns {
	return r.ranFeedOperationLogDo.Columns(cols...)
}

func (r *ranFeedOperationLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *ranFeedOperationLog) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 14)
	r.fieldMap["id"] = r.ID
	r.fieldMap["admin_id"] = r.AdminID
	r.fieldMap["action"] = r.Action
	r.fieldMap["target_type"] = r.TargetType
	r.fieldMap["target_id"] = r.TargetID
	r.fieldMap["payload"] = r.Payload
	r.fieldMap["result"] = r.Result
	r.fieldMap["ip"] = r.IP
	r.fieldMap["version"] = r.Version
	r.fieldMap["is_deleted"] = r.IsDeleted
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["updated_by"] = r.UpdatedBy
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r ranFeedOperationLog) clone(db *gorm.DB) ranFeedOperationLog {
	r.ranFeedOperationLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r ranFeedOperationLog) replaceDB(db *gorm.DB) ranFeedOperationLog {
	r.ranFeedOperationLogDo.ReplaceDB(db)
	return r
}

type ranFeedOperationLogDo struct{ gen.DO }

type IRanFeedOperationLogDo interface {
	gen.SubQuery
	Debug() IRanFeedOperationLogDo
	WithContext(ctx context.Context) IRanFeedOperationLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRanFeedOperationLogDo
	WriteDB() IRanFeedOperationLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRanFeedOperationLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRanFeedOperationLogDo
	Not(conds ...gen.Condition) IRanFeedOperationLogDo
	Or(conds ...gen.Condition) IRanFeedOperationLogDo
	Select(conds ...field.Expr) IRanFeedOperationLogDo
	Where(conds ...gen.Condition) IRanFeedOperationLogDo
	Order(conds ...field.Expr) IRanFeedOperationLogDo
	Distinct(cols ...field.Expr) IRanFeedOperationLogDo
	Omit(cols ...field.Expr) IRanFeedOperationLogDo
	Join(table schema.Tabler, on ...field.Expr) IRanFeedOperationLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedOperationLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedOperationLogDo
	Group(cols ...field.Expr) IRanFeedOperationLogDo
	Having(conds ...gen.Condition) IRanFeedOperationLogDo
	Limit(limit int) IRanFeedOperationLogDo
	Offset(offset int) IRanFeedOperationLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedOperationLogDo
	Unscoped() IRanFeedOperationLogDo
	Create(values ...*model.RanFeedOperationLog) error
	CreateInBatches(values []*model.RanFeedOperationLog, batchSize int) error
	Save(values ...*model.RanFeedOperationLog) error
	First() (*model.RanFeedOperationLog, error)
	Take() (*model.RanFeedOperationLog, error)
	Last() (*model.RanFeedOperationLog, error)
	Find() ([]*model.RanFeedOperationLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedOperationLog, err error)
	FindInBatches(result *[]*model.RanFeedOperationLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RanFeedOperationLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRanFeedOperationLogDo
	Assign(attrs ...field.AssignExpr) IRanFeedOperationLogDo
	Joins(fields ...field.RelationField) IRanFeedOperationLogDo
	Preload(fields ...field.RelationField) IRanFeedOperationLogDo
	FirstOrInit() (*model.RanFeedOperationLog, error)
	FirstOrCreate() (*model.RanFeedOperationLog, error)
	FindByPage(offset int, limit int) (result []*model.RanFeedOperationLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRanFeedOperationLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r ranFeedOperationLogDo) Debug() IRanFeedOperationLogDo {
	return r.withDO(r.DO.Debug())
}

func (r ranFeedOperationLogDo) WithContext(ctx context.Context) IRanFeedOperationLogDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r ranFeedOperationLogDo) ReadDB() IRanFeedOperationLogDo {
	return r.Clauses(dbresolver.Read)
}

func (r ranFeedOperationLogDo) WriteDB() IRanFeedOperationLogDo {
	return r.Clauses(dbresolver.Write)
}

func (r ranFeedOperationLogDo) Session(config *gorm.Session) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Session(config))
}

func (r ranFeedOperationLogDo) Clauses(conds ...clause.Expression) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r ranFeedOperationLogDo) Returning(value interface{}, columns ...string) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r ranFeedOperationLogDo) Not(conds ...gen.Condition) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r ranFeedOperationLogDo) Or(conds ...gen.Condition) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r ranFeedOperationLogDo) Select(conds ...field.Expr) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r ranFeedOperationLogDo) Where(conds ...gen.Condition) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r ranFeedOperationLogDo) Order(conds ...field.Expr) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r ranFeedOperationLogDo) Distinct(cols ...field.Expr) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r ranFeedOperationLogDo) Omit(cols ...field.Expr) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r ranFeedOperationLogDo) Join(table schema.Tabler, on ...field.Expr) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r ranFeedOperationLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedOperationLogDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r ranFeedOperationLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedOperationLogDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r ranFeedOperationLogDo) Group(cols ...field.Expr) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r ranFeedOperationLogDo) Having(conds ...gen.Condition) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r ranFeedOperationLogDo) Limit(limit int) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r ranFeedOperationLogDo) Offset(offset int) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r ranFeedOperationLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r ranFeedOperationLogDo) Unscoped() IRanFeedOperationLogDo {
	return r.withDO(r.DO.Unscoped())
}

func (r ranFeedOperationLogDo) Create(values ...*model.RanFeedOperationLog) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r ranFeedOperationLogDo) CreateInBatches(values []*model.RanFeedOperationLog, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r ranFeedOperationLogDo) Save(values ...*model.RanFeedOperationLog) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r ranFeedOperationLogDo) First() (*model.RanFeedOperationLog, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedOperationLog), nil
	}
}

func (r ranFeedOperationLogDo) Take() (*model.RanFeedOperationLog, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedOperationLog), nil
	}
}

func (r ranFeedOperationLogDo) Last() (*model.RanFeedOperationLog, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedOperationLog), nil
	}
}

func (r ranFeedOperationLogDo) Find() ([]*model.RanFeedOperationLog, error) {
	result, err := r.DO.Find()
	return result.([]*model.RanFeedOperationLog), err
}

func (r ranFeedOperationLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedOperationLog, err error) {
	buf := make([]*model.RanFeedOperationLog, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r ranFeedOperationLogDo) FindInBatches(result *[]*model.RanFeedOperationLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r ranFeedOperationLogDo) Attrs(attrs ...field.AssignExpr) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r ranFeedOperationLogDo) Assign(attrs ...field.AssignExpr) IRanFeedOperationLogDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r ranFeedOperationLogDo) Joins(fields ...field.RelationField) IRanFeedOperationLogDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r ranFeedOperationLogDo) Preload(fields ...field.RelationField) IRanFeedOperationLogDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r ranFeedOperationLogDo) FirstOrInit() (*model.RanFeedOperationLog, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedOperationLog), nil
	}
}

func (r ranFeedOperationLogDo) FirstOrCreate() (*model.RanFeedOperationLog, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedOperationLog), nil
	}
}

func (r ranFeedOperationLogDo) FindByPage(offset int, limit int) (result []*model.RanFeedOperationLog, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r ranFeedOperationLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r ranFeedOperationLogDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r ranFeedOperationLogDo) Delete(models ...*model.RanFeedOperationLog) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *ranFeedOperationLogDo) withDO(do gen.Dao) *ranFeedOperationLogDo {
	r.DO = *do.(*gen.DO)
	return r
}
