// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ran-feed/app/rpc/admin/internal/entity/model"
)

func newRanFeedLoginLog(db *gorm.DB, opts ...gen.DOOption) ranFeedLoginLog {
	_ranFeedLoginLog := ranFeedLoginLog{}

	_ranFeedLoginLog.ranFeedLoginLogDo.UseDB(db, opts...)
	_ranFeedLoginLog.ranFeedLoginLogDo.UseModel(&model.RanFeedLoginLog{})

	tableName := _ranFeedLoginLog.ranFeedLoginLogDo.TableName()
	_ranFeedLoginLog.ALL = field.NewAsterisk(tableName)
	_ranFeedLoginLog.ID = field.NewInt64(tableName, "id")
	_ranFeedLoginLog.AdminID = field.NewInt64(tableName, "admin_id")
	_ranFeedLoginLog.Username = field.NewString(tableName, "username")
	_ranFeedLoginLog.IP = field.NewString(tableName, "ip")
	_ranFeedLoginLog.UserAgent = field.NewString(tableName, "user_agent")
	_ranFeedLoginLog.Status = field.NewInt32(tableName, "status")
	_ranFeedLoginLog.Msg = field.NewString(tableName, "msg")
	_ranFeedLoginLog.Version = field.NewInt32(tableName, "version")
	_ranFeedLoginLog.IsDeleted = field.NewInt32(tableName, "is_deleted")
	_ranFeedLoginLog.CreatedBy = field.NewInt64(tableName, "created_by")
	_ranFeedLoginLog.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_ranFeedLoginLog.CreatedAt = field.NewTime(tableName, "created_at")
	_ranFeedLoginLog.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ranFeedLoginLog.fillFieldMap()

	return _ranFeedLoginLog
}

// ranFeedLoginLog 后台登录日志表
type ranFeedLoginLog struct {
	ranFeedLoginLogDo ranFeedLoginLogDo

	ALL       field.Asterisk
	ID        field.Int64  // 登录日志ID
	AdminID   field.Int64  // 管理员ID 成功时填 失败为0
	Username  field.String // 登录账号 未认证也记 供失败排查
	IP        field.String // 来源IP
	UserAgent field.String // UA 原始串
	Status    field.Int32  // 登录成败 0=失败 1=成功
	Msg       field.String // 提示消息 成功/失败原因
	Version   field.Int32  // 版本号（乐观锁）
	IsDeleted field.Int32  // 逻辑删除 0=正常 1=删除
	CreatedBy field.Int64  // 创建人
	UpdatedBy field.Int64  // 最后修改人
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (r ranFeedLoginLog) Table(newTableName string) *ranFeedLoginLog {
	r.ranFeedLoginLogDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r ranFeedLoginLog) As(alias string) *ranFeedLoginLog {
	r.ranFeedLoginLogDo.DO = *(r.ranFeedLoginLogDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *ranFeedLoginLog) updateTableName(table string) *ranFeedLoginLog {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.AdminID = field.NewInt64(table, "admin_id")
	r.Username = field.NewString(table, "username")
	r.IP = field.NewString(table, "ip")
	r.UserAgent = field.NewString(table, "user_agent")
	r.Status = field.NewInt32(table, "status")
	r.Msg = field.NewString(table, "msg")
	r.Version = field.NewInt32(table, "version")
	r.IsDeleted = field.NewInt32(table, "is_deleted")
	r.CreatedBy = field.NewInt64(table, "created_by")
	r.UpdatedBy = field.NewInt64(table, "updated_by")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *ranFeedLoginLog) WithContext(ctx context.Context) IRanFeedLoginLogDo {
	return r.ranFeedLoginLogDo.WithContext(ctx)
}

func (r ranFeedLoginLog) TableName() string { return r.ranFeedLoginLogDo.TableName() }

func (r ranFeedLoginLog) Alias() string { return r.ranFeedLoginLogDo.Alias() }

func (r ranFeedLoginLog) Columns(cols ...field.Expr) gen.Columns {
	return r.ranFeedLoginLogDo.Columns(cols...)
}

func (r *ranFeedLoginLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *ranFeedLoginLog) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 13)
	r.fieldMap["id"] = r.ID
	r.fieldMap["admin_id"] = r.AdminID
	r.fieldMap["username"] = r.Username
	r.fieldMap["ip"] = r.IP
	r.fieldMap["user_agent"] = r.UserAgent
	r.fieldMap["status"] = r.Status
	r.fieldMap["msg"] = r.Msg
	r.fieldMap["version"] = r.Version
	r.fieldMap["is_deleted"] = r.IsDeleted
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["updated_by"] = r.UpdatedBy
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r ranFeedLoginLog) clone(db *gorm.DB) ranFeedLoginLog {
	r.ranFeedLoginLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r ranFeedLoginLog) replaceDB(db *gorm.DB) ranFeedLoginLog {
	r.ranFeedLoginLogDo.ReplaceDB(db)
	return r
}

type ranFeedLoginLogDo struct{ gen.DO }

type IRanFeedLoginLogDo interface {
	gen.SubQuery
	Debug() IRanFeedLoginLogDo
	WithContext(ctx context.Context) IRanFeedLoginLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRanFeedLoginLogDo
	WriteDB() IRanFeedLoginLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRanFeedLoginLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRanFeedLoginLogDo
	Not(conds ...gen.Condition) IRanFeedLoginLogDo
	Or(conds ...gen.Condition) IRanFeedLoginLogDo
	Select(conds ...field.Expr) IRanFeedLoginLogDo
	Where(conds ...gen.Condition) IRanFeedLoginLogDo
	Order(conds ...field.Expr) IRanFeedLoginLogDo
	Distinct(cols ...field.Expr) IRanFeedLoginLogDo
	Omit(cols ...field.Expr) IRanFeedLoginLogDo
	Join(table schema.Tabler, on ...field.Expr) IRanFeedLoginLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedLoginLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedLoginLogDo
	Group(cols ...field.Expr) IRanFeedLoginLogDo
	Having(conds ...gen.Condition) IRanFeedLoginLogDo
	Limit(limit int) IRanFeedLoginLogDo
	Offset(offset int) IRanFeedLoginLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedLoginLogDo
	Unscoped() IRanFeedLoginLogDo
	Create(values ...*model.RanFeedLoginLog) error
	CreateInBatches(values []*model.RanFeedLoginLog, batchSize int) error
	Save(values ...*model.RanFeedLoginLog) error
	First() (*model.RanFeedLoginLog, error)
	Take() (*model.RanFeedLoginLog, error)
	Last() (*model.RanFeedLoginLog, error)
	Find() ([]*model.RanFeedLoginLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedLoginLog, err error)
	FindInBatches(result *[]*model.RanFeedLoginLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RanFeedLoginLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRanFeedLoginLogDo
	Assign(attrs ...field.AssignExpr) IRanFeedLoginLogDo
	Joins(fields ...field.RelationField) IRanFeedLoginLogDo
	Preload(fields ...field.RelationField) IRanFeedLoginLogDo
	FirstOrInit() (*model.RanFeedLoginLog, error)
	FirstOrCreate() (*model.RanFeedLoginLog, error)
	FindByPage(offset int, limit int) (result []*model.RanFeedLoginLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRanFeedLoginLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r ranFeedLoginLogDo) Debug() IRanFeedLoginLogDo {
	return r.withDO(r.DO.Debug())
}

func (r ranFeedLoginLogDo) WithContext(ctx context.Context) IRanFeedLoginLogDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r ranFeedLoginLogDo) ReadDB() IRanFeedLoginLogDo {
	return r.Clauses(dbresolver.Read)
}

func (r ranFeedLoginLogDo) WriteDB() IRanFeedLoginLogDo {
	return r.Clauses(dbresolver.Write)
}

func (r ranFeedLoginLogDo) Session(config *gorm.Session) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Session(config))
}

func (r ranFeedLoginLogDo) Clauses(conds ...clause.Expression) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r ranFeedLoginLogDo) Returning(value interface{}, columns ...string) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r ranFeedLoginLogDo) Not(conds ...gen.Condition) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r ranFeedLoginLogDo) Or(conds ...gen.Condition) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r ranFeedLoginLogDo) Select(conds ...field.Expr) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r ranFeedLoginLogDo) Where(conds ...gen.Condition) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r ranFeedLoginLogDo) Order(conds ...field.Expr) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r ranFeedLoginLogDo) Distinct(cols ...field.Expr) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r ranFeedLoginLogDo) Omit(cols ...field.Expr) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r ranFeedLoginLogDo) Join(table schema.Tabler, on ...field.Expr) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r ranFeedLoginLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedLoginLogDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r ranFeedLoginLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedLoginLogDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r ranFeedLoginLogDo) Group(cols ...field.Expr) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r ranFeedLoginLogDo) Having(conds ...gen.Condition) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r ranFeedLoginLogDo) Limit(limit int) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r ranFeedLoginLogDo) Offset(offset int) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r ranFeedLoginLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r ranFeedLoginLogDo) Unscoped() IRanFeedLoginLogDo {
	return r.withDO(r.DO.Unscoped())
}

func (r ranFeedLoginLogDo) Create(values ...*model.RanFeedLoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r ranFeedLoginLogDo) CreateInBatches(values []*model.RanFeedLoginLog, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r ranFeedLoginLogDo) Save(values ...*model.RanFeedLoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r ranFeedLoginLogDo) First() (*model.RanFeedLoginLog, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedLoginLog), nil
	}
}

func (r ranFeedLoginLogDo) Take() (*model.RanFeedLoginLog, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedLoginLog), nil
	}
}

func (r ranFeedLoginLogDo) Last() (*model.RanFeedLoginLog, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedLoginLog), nil
	}
}

func (r ranFeedLoginLogDo) Find() ([]*model.RanFeedLoginLog, error) {
	result, err := r.DO.Find()
	return result.([]*model.RanFeedLoginLog), err
}

func (r ranFeedLoginLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedLoginLog, err error) {
	buf := make([]*model.RanFeedLoginLog, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r ranFeedLoginLogDo) FindInBatches(result *[]*model.RanFeedLoginLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r ranFeedLoginLogDo) Attrs(attrs ...field.AssignExpr) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r ranFeedLoginLogDo) Assign(attrs ...field.AssignExpr) IRanFeedLoginLogDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r ranFeedLoginLogDo) Joins(fields ...field.RelationField) IRanFeedLoginLogDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r ranFeedLoginLogDo) Preload(fields ...field.RelationField) IRanFeedLoginLogDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r ranFeedLoginLogDo) FirstOrInit() (*model.RanFeedLoginLog, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedLoginLog), nil
	}
}

func (r ranFeedLoginLogDo) FirstOrCreate() (*model.RanFeedLoginLog, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedLoginLog), nil
	}
}

func (r ranFeedLoginLogDo) FindByPage(offset int, limit int) (result []*model.RanFeedLoginLog, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r ranFeedLoginLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r ranFeedLoginLogDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r ranFeedLoginLogDo) Delete(models ...*model.RanFeedLoginLog) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *ranFeedLoginLogDo) withDO(do gen.Dao) *ranFeedLoginLogDo {
	r.DO = *do.(*gen.DO)
	return r
}
