// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRanFeedAdminRolePermission = "ran_feed_admin_role_permission"

// RanFeedAdminRolePermission 后台角色-权限点关系表
type RanFeedAdminRolePermission struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	RoleID       int64     `gorm:"column:role_id;not null;comment:角色ID" json:"role_id"`                                 // 角色ID
	PermissionID int64     `gorm:"column:permission_id;not null;comment:权限点ID" json:"permission_id"`                    // 权限点ID
	Version      int32     `gorm:"column:version;not null;default:1;comment:版本号（乐观锁）" json:"version"`                   // 版本号（乐观锁）
	IsDeleted    int32     `gorm:"column:is_deleted;not null;comment:逻辑删除 0=正常 1=删除" json:"is_deleted"`                 // 逻辑删除 0=正常 1=删除
	CreatedBy    int64     `gorm:"column:created_by;not null;comment:创建人" json:"created_by"`                            // 创建人
	UpdatedBy    int64     `gorm:"column:updated_by;not null;comment:最后修改人" json:"updated_by"`                          // 最后修改人
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName RanFeedAdminRolePermission's table name
func (*RanFeedAdminRolePermission) TableName() string {
	return TableNameRanFeedAdminRolePermission
}
