// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package contentservice

import (
	"context"

	"ran-feed/app/rpc/content/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticlePublishReq            = content.ArticlePublishReq
	ArticlePublishRes            = content.ArticlePublishRes
	BackfillFollowInboxReq       = content.BackfillFollowInboxReq
	BackfillFollowInboxRes       = content.BackfillFollowInboxRes
	ContentDetail                = content.ContentDetail
	ContentItem                  = content.ContentItem
	ContentUploadsCredentialsReq = content.ContentUploadsCredentialsReq
	ContentUploadsCredentialsRes = content.ContentUploadsCredentialsRes
	DeleteContentReq             = content.DeleteContentReq
	DeleteContentRes             = content.DeleteContentRes
	FollowFeedItem               = content.FollowFeedItem
	FollowFeedReq                = content.FollowFeedReq
	FollowFeedRes                = content.FollowFeedRes
	GetContentDetailReq          = content.GetContentDetailReq
	GetContentDetailRes          = content.GetContentDetailRes
	GetUserContentCountReq       = content.GetUserContentCountReq
	GetUserContentCountRes       = content.GetUserContentCountRes
	OssFormData                  = content.OssFormData
	PageReq                      = content.PageReq
	PageRes                      = content.PageRes
	RecommendFeedReq             = content.RecommendFeedReq
	RecommendFeedRes             = content.RecommendFeedRes
	UserFavoriteFeedReq          = content.UserFavoriteFeedReq
	UserFavoriteFeedRes          = content.UserFavoriteFeedRes
	UserPublishFeedReq           = content.UserPublishFeedReq
	UserPublishFeedRes           = content.UserPublishFeedRes
	VideoPublishReq              = content.VideoPublishReq
	VideoPublishRes              = content.VideoPublishRes

	ContentService interface {
		Uploads(ctx context.Context, in *ContentUploadsCredentialsReq, opts ...grpc.CallOption) (*ContentUploadsCredentialsRes, error)
		PublishArticle(ctx context.Context, in *ArticlePublishReq, opts ...grpc.CallOption) (*ArticlePublishRes, error)
		PublishVideo(ctx context.Context, in *VideoPublishReq, opts ...grpc.CallOption) (*VideoPublishRes, error)
		GetUserContentCount(ctx context.Context, in *GetUserContentCountReq, opts ...grpc.CallOption) (*GetUserContentCountRes, error)
		DeleteContent(ctx context.Context, in *DeleteContentReq, opts ...grpc.CallOption) (*DeleteContentRes, error)
		GetContentDetail(ctx context.Context, in *GetContentDetailReq, opts ...grpc.CallOption) (*GetContentDetailRes, error)
		BackfillFollowInbox(ctx context.Context, in *BackfillFollowInboxReq, opts ...grpc.CallOption) (*BackfillFollowInboxRes, error)
	}

	defaultContentService struct {
		cli zrpc.Client
	}
)

func NewContentService(cli zrpc.Client) ContentService {
	return &defaultContentService{
		cli: cli,
	}
}

func (m *defaultContentService) Uploads(ctx context.Context, in *ContentUploadsCredentialsReq, opts ...grpc.CallOption) (*ContentUploadsCredentialsRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.Uploads(ctx, in, opts...)
}

func (m *defaultContentService) PublishArticle(ctx context.Context, in *ArticlePublishReq, opts ...grpc.CallOption) (*ArticlePublishRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PublishArticle(ctx, in, opts...)
}

func (m *defaultContentService) PublishVideo(ctx context.Context, in *VideoPublishReq, opts ...grpc.CallOption) (*VideoPublishRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}

func (m *defaultContentService) GetUserContentCount(ctx context.Context, in *GetUserContentCountReq, opts ...grpc.CallOption) (*GetUserContentCountRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.GetUserContentCount(ctx, in, opts...)
}

func (m *defaultContentService) DeleteContent(ctx context.Context, in *DeleteContentReq, opts ...grpc.CallOption) (*DeleteContentRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.DeleteContent(ctx, in, opts...)
}

func (m *defaultContentService) GetContentDetail(ctx context.Context, in *GetContentDetailReq, opts ...grpc.CallOption) (*GetContentDetailRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.GetContentDetail(ctx, in, opts...)
}

func (m *defaultContentService) BackfillFollowInbox(ctx context.Context, in *BackfillFollowInboxReq, opts ...grpc.CallOption) (*BackfillFollowInboxRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.BackfillFollowInbox(ctx, in, opts...)
}
