// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: content.proto

package contentservice

import (
	"context"

	"ran-feed/app/rpc/content/content"

	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticlePublishReq            = content.ArticlePublishReq
	ArticlePublishRes            = content.ArticlePublishRes
	BackfillFollowInboxReq       = content.BackfillFollowInboxReq
	BackfillFollowInboxRes       = content.BackfillFollowInboxRes
	ContentDetail                = content.ContentDetail
	ContentUploadsCredentialsReq = content.ContentUploadsCredentialsReq
	ContentUploadsCredentialsRes = content.ContentUploadsCredentialsRes
	DeleteContentReq             = content.DeleteContentReq
	GetContentDetailReq          = content.GetContentDetailReq
	GetContentDetailRes          = content.GetContentDetailRes
	GetUserContentCountReq       = content.GetUserContentCountReq
	GetUserContentCountRes       = content.GetUserContentCountRes
	OssFormData                  = content.OssFormData
	PurgeFolloweeFromInboxReq    = content.PurgeFolloweeFromInboxReq
	PurgeFolloweeFromInboxRes    = content.PurgeFolloweeFromInboxRes
	VideoPublishReq              = content.VideoPublishReq
	VideoPublishRes              = content.VideoPublishRes

	ContentService interface {
		Uploads(ctx context.Context, in *ContentUploadsCredentialsReq, opts ...grpc.CallOption) (*ContentUploadsCredentialsRes, error)
		PublishArticle(ctx context.Context, in *ArticlePublishReq, opts ...grpc.CallOption) (*ArticlePublishRes, error)
		PublishVideo(ctx context.Context, in *VideoPublishReq, opts ...grpc.CallOption) (*VideoPublishRes, error)
		GetUserContentCount(ctx context.Context, in *GetUserContentCountReq, opts ...grpc.CallOption) (*GetUserContentCountRes, error)
		DeleteContent(ctx context.Context, in *DeleteContentReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
		GetContentDetail(ctx context.Context, in *GetContentDetailReq, opts ...grpc.CallOption) (*GetContentDetailRes, error)
		BackfillFollowInbox(ctx context.Context, in *BackfillFollowInboxReq, opts ...grpc.CallOption) (*BackfillFollowInboxRes, error)
		PurgeFolloweeFromInbox(ctx context.Context, in *PurgeFolloweeFromInboxReq, opts ...grpc.CallOption) (*PurgeFolloweeFromInboxRes, error)
	}

	defaultContentService struct {
		cli zrpc.Client
	}
)

func NewContentService(cli zrpc.Client) ContentService {
	return &defaultContentService{
		cli: cli,
	}
}

func (m *defaultContentService) Uploads(ctx context.Context, in *ContentUploadsCredentialsReq, opts ...grpc.CallOption) (*ContentUploadsCredentialsRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.Uploads(ctx, in, opts...)
}

func (m *defaultContentService) PublishArticle(ctx context.Context, in *ArticlePublishReq, opts ...grpc.CallOption) (*ArticlePublishRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PublishArticle(ctx, in, opts...)
}

func (m *defaultContentService) PublishVideo(ctx context.Context, in *VideoPublishReq, opts ...grpc.CallOption) (*VideoPublishRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}

func (m *defaultContentService) GetUserContentCount(ctx context.Context, in *GetUserContentCountReq, opts ...grpc.CallOption) (*GetUserContentCountRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.GetUserContentCount(ctx, in, opts...)
}

func (m *defaultContentService) DeleteContent(ctx context.Context, in *DeleteContentReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.DeleteContent(ctx, in, opts...)
}

func (m *defaultContentService) GetContentDetail(ctx context.Context, in *GetContentDetailReq, opts ...grpc.CallOption) (*GetContentDetailRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.GetContentDetail(ctx, in, opts...)
}

func (m *defaultContentService) BackfillFollowInbox(ctx context.Context, in *BackfillFollowInboxReq, opts ...grpc.CallOption) (*BackfillFollowInboxRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.BackfillFollowInbox(ctx, in, opts...)
}

func (m *defaultContentService) PurgeFolloweeFromInbox(ctx context.Context, in *PurgeFolloweeFromInboxReq, opts ...grpc.CallOption) (*PurgeFolloweeFromInboxRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PurgeFolloweeFromInbox(ctx, in, opts...)
}
