// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: content.proto

package contentservice

import (
	"context"

	"ran-feed/app/rpc/content/content"

	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticlePublishReq            = content.ArticlePublishReq
	ArticlePublishRes            = content.ArticlePublishRes
	BackfillFollowInboxReq       = content.BackfillFollowInboxReq
	BackfillFollowInboxRes       = content.BackfillFollowInboxRes
	ClearUserFavoriteCacheReq    = content.ClearUserFavoriteCacheReq
	ContentDetail                = content.ContentDetail
	ContentUploadsCredentialsReq = content.ContentUploadsCredentialsReq
	ContentUploadsCredentialsRes = content.ContentUploadsCredentialsRes
	DeleteContentReq             = content.DeleteContentReq
	GetContentDetailReq          = content.GetContentDetailReq
	GetContentDetailRes          = content.GetContentDetailRes
	GetUserContentCountReq       = content.GetUserContentCountReq
	GetUserContentCountRes       = content.GetUserContentCountRes
	MyContentItem                = content.MyContentItem
	MyContentListReq             = content.MyContentListReq
	MyContentListRes             = content.MyContentListRes
	PurgeFolloweeFromInboxReq    = content.PurgeFolloweeFromInboxReq
	PurgeFolloweeFromInboxRes    = content.PurgeFolloweeFromInboxRes
	SaveArticleDraftReq          = content.SaveArticleDraftReq
	SaveArticleDraftRes          = content.SaveArticleDraftRes
	SaveVideoDraftReq            = content.SaveVideoDraftReq
	SaveVideoDraftRes            = content.SaveVideoDraftRes
	SubmitContentReq             = content.SubmitContentReq
	SubmitContentRes             = content.SubmitContentRes
	VideoPublishReq              = content.VideoPublishReq
	VideoPublishRes              = content.VideoPublishRes

	ContentService interface {
		Uploads(ctx context.Context, in *ContentUploadsCredentialsReq, opts ...grpc.CallOption) (*ContentUploadsCredentialsRes, error)
		PublishArticle(ctx context.Context, in *ArticlePublishReq, opts ...grpc.CallOption) (*ArticlePublishRes, error)
		PublishVideo(ctx context.Context, in *VideoPublishReq, opts ...grpc.CallOption) (*VideoPublishRes, error)
		SaveArticleDraft(ctx context.Context, in *SaveArticleDraftReq, opts ...grpc.CallOption) (*SaveArticleDraftRes, error)
		SaveVideoDraft(ctx context.Context, in *SaveVideoDraftReq, opts ...grpc.CallOption) (*SaveVideoDraftRes, error)
		SubmitContent(ctx context.Context, in *SubmitContentReq, opts ...grpc.CallOption) (*SubmitContentRes, error)
		MyContentList(ctx context.Context, in *MyContentListReq, opts ...grpc.CallOption) (*MyContentListRes, error)
		GetUserContentCount(ctx context.Context, in *GetUserContentCountReq, opts ...grpc.CallOption) (*GetUserContentCountRes, error)
		DeleteContent(ctx context.Context, in *DeleteContentReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
		GetContentDetail(ctx context.Context, in *GetContentDetailReq, opts ...grpc.CallOption) (*GetContentDetailRes, error)
		BackfillFollowInbox(ctx context.Context, in *BackfillFollowInboxReq, opts ...grpc.CallOption) (*BackfillFollowInboxRes, error)
		PurgeFolloweeFromInbox(ctx context.Context, in *PurgeFolloweeFromInboxReq, opts ...grpc.CallOption) (*PurgeFolloweeFromInboxRes, error)
		ClearUserFavoriteCache(ctx context.Context, in *ClearUserFavoriteCacheReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	}

	defaultContentService struct {
		cli zrpc.Client
	}
)

func NewContentService(cli zrpc.Client) ContentService {
	return &defaultContentService{
		cli: cli,
	}
}

func (m *defaultContentService) Uploads(ctx context.Context, in *ContentUploadsCredentialsReq, opts ...grpc.CallOption) (*ContentUploadsCredentialsRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.Uploads(ctx, in, opts...)
}

func (m *defaultContentService) PublishArticle(ctx context.Context, in *ArticlePublishReq, opts ...grpc.CallOption) (*ArticlePublishRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PublishArticle(ctx, in, opts...)
}

func (m *defaultContentService) PublishVideo(ctx context.Context, in *VideoPublishReq, opts ...grpc.CallOption) (*VideoPublishRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}

func (m *defaultContentService) SaveArticleDraft(ctx context.Context, in *SaveArticleDraftReq, opts ...grpc.CallOption) (*SaveArticleDraftRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.SaveArticleDraft(ctx, in, opts...)
}

func (m *defaultContentService) SaveVideoDraft(ctx context.Context, in *SaveVideoDraftReq, opts ...grpc.CallOption) (*SaveVideoDraftRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.SaveVideoDraft(ctx, in, opts...)
}

func (m *defaultContentService) SubmitContent(ctx context.Context, in *SubmitContentReq, opts ...grpc.CallOption) (*SubmitContentRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.SubmitContent(ctx, in, opts...)
}

func (m *defaultContentService) MyContentList(ctx context.Context, in *MyContentListReq, opts ...grpc.CallOption) (*MyContentListRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.MyContentList(ctx, in, opts...)
}

func (m *defaultContentService) GetUserContentCount(ctx context.Context, in *GetUserContentCountReq, opts ...grpc.CallOption) (*GetUserContentCountRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.GetUserContentCount(ctx, in, opts...)
}

func (m *defaultContentService) DeleteContent(ctx context.Context, in *DeleteContentReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.DeleteContent(ctx, in, opts...)
}

func (m *defaultContentService) GetContentDetail(ctx context.Context, in *GetContentDetailReq, opts ...grpc.CallOption) (*GetContentDetailRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.GetContentDetail(ctx, in, opts...)
}

func (m *defaultContentService) BackfillFollowInbox(ctx context.Context, in *BackfillFollowInboxReq, opts ...grpc.CallOption) (*BackfillFollowInboxRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.BackfillFollowInbox(ctx, in, opts...)
}

func (m *defaultContentService) PurgeFolloweeFromInbox(ctx context.Context, in *PurgeFolloweeFromInboxReq, opts ...grpc.CallOption) (*PurgeFolloweeFromInboxRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PurgeFolloweeFromInbox(ctx, in, opts...)
}

func (m *defaultContentService) ClearUserFavoriteCache(ctx context.Context, in *ClearUserFavoriteCacheReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.ClearUserFavoriteCache(ctx, in, opts...)
}
