// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRanFeedContent = "ran_feed_content"

// RanFeedContent ç»Ÿä¸€å†…å®¹ä¸»è¡¨
type RanFeedContent struct {
	ID             int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:å†…å®¹ID" json:"id"`                                // å†…å®¹ID
	UserID         int64      `gorm:"column:user_id;not null;comment:å‘å¸ƒè€…ï¼ˆå†…å®¹ä½œè€…ï¼‰" json:"user_id"`                        // å‘å¸ƒè€…ï¼ˆå†…å®¹ä½œè€…ï¼‰
	ContentType    int32      `gorm:"column:content_type;not null;comment:å†…å®¹ç±»åž‹ 10=æ–‡ç«  20=è§†é¢‘" json:"content_type"`         // å†…å®¹ç±»åž‹ 10=æ–‡ç«  20=è§†é¢‘
	Status         int32      `gorm:"column:status;not null;comment:çŠ¶æ€ 10=è‰ç¨¿ 20=å¤„ç†ä¸­ 30=å·²å‘å¸ƒ 40=å¤±è´¥" json:"status"` // çŠ¶æ€ 10=è‰ç¨¿ 20=å¤„ç†ä¸­ 30=å·²å‘å¸ƒ 40=å¤±è´¥
	Visibility     int32      `gorm:"column:visibility;not null;default:1;comment:å¯è§æ€§ 10=å…¬å¼€ 20=ç§å¯†" json:"visibility"`      // å¯è§æ€§ 10=å…¬å¼€ 20=ç§å¯†
	LikeCount      int64      `gorm:"column:like_count;not null;comment:ç‚¹èµžæ•°" json:"like_count"`                                    // ç‚¹èµžæ•°
	FavoriteCount  int64      `gorm:"column:favorite_count;not null;comment:æ”¶è—æ•°" json:"favorite_count"`                            // æ”¶è—æ•°
	CommentCount   int64      `gorm:"column:comment_count;not null;comment:è¯„è®ºæ•°" json:"comment_count"`                              // è¯„è®ºæ•°
	HotScore       float64    `gorm:"column:hot_score;not null;comment:çƒ­åº¦åˆ†" json:"hot_score"`                                      // çƒ­åº¦åˆ†
	LastHotScoreAt *time.Time `gorm:"column:last_hot_score_at;comment:çƒ­åº¦åˆ†æœ€åŽæ›´æ–°æ—¶é—´" json:"last_hot_score_at"`             // çƒ­åº¦åˆ†æœ€åŽæ›´æ–°æ—¶é—´
	Version        int32      `gorm:"column:version;not null;default:1;comment:ç‰ˆæœ¬å·ï¼ˆä¹è§‚é”ï¼‰" json:"version"`                 // ç‰ˆæœ¬å·ï¼ˆä¹è§‚é”ï¼‰
	IsDeleted      int32      `gorm:"column:is_deleted;not null;comment:é€»è¾‘åˆ é™¤ 0=æ­£å¸¸ 1=åˆ é™¤" json:"is_deleted"`               // é€»è¾‘åˆ é™¤ 0=æ­£å¸¸ 1=åˆ é™¤
	CreatedBy      int64      `gorm:"column:created_by;not null;comment:åˆ›å»ºäºº" json:"created_by"`                                    // åˆ›å»ºäºº
	UpdatedBy      int64      `gorm:"column:updated_by;not null;comment:æœ€åŽä¿®æ”¹äºº" json:"updated_by"`                              // æœ€åŽä¿®æ”¹äºº
	CreatedAt      time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:åˆ›å»ºæ—¶é—´" json:"created_at"`       // åˆ›å»ºæ—¶é—´
	PublishedAt    *time.Time `gorm:"column:published_at;comment:å‘å¸ƒæ—¶é—´" json:"published_at"`                                      // å‘å¸ƒæ—¶é—´
	UpdatedAt      time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:æ›´æ–°æ—¶é—´" json:"updated_at"`       // æ›´æ–°æ—¶é—´
}

// TableName RanFeedContent's table name
func (*RanFeedContent) TableName() string {
	return TableNameRanFeedContent
}
