// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package server

import (
	"context"

	"ran-feed/app/rpc/search/internal/logic/searchservice"
	"ran-feed/app/rpc/search/internal/svc"
	"ran-feed/app/rpc/search/search"
)

type SearchServiceServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServiceServer
}

func NewSearchServiceServer(svcCtx *svc.ServiceContext) *SearchServiceServer {
	return &SearchServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchServiceServer) SearchContent(ctx context.Context, in *search.SearchContentReq) (*search.SearchContentRes, error) {
	l := searchservicelogic.NewSearchContentLogic(ctx, s.svcCtx)
	return l.SearchContent(in)
}

func (s *SearchServiceServer) SearchUser(ctx context.Context, in *search.SearchUserReq) (*search.SearchUserRes, error) {
	l := searchservicelogic.NewSearchUserLogic(ctx, s.svcCtx)
	return l.SearchUser(in)
}

func (s *SearchServiceServer) RecordHistory(ctx context.Context, in *search.RecordHistoryReq) (*search.RecordHistoryRes, error) {
	l := searchservicelogic.NewRecordHistoryLogic(ctx, s.svcCtx)
	return l.RecordHistory(in)
}

func (s *SearchServiceServer) ListHistory(ctx context.Context, in *search.ListHistoryReq) (*search.ListHistoryRes, error) {
	l := searchservicelogic.NewListHistoryLogic(ctx, s.svcCtx)
	return l.ListHistory(in)
}

func (s *SearchServiceServer) DeleteHistory(ctx context.Context, in *search.DeleteHistoryReq) (*search.DeleteHistoryRes, error) {
	l := searchservicelogic.NewDeleteHistoryLogic(ctx, s.svcCtx)
	return l.DeleteHistory(in)
}
