// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: app/rpc/notification/proto/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotifyType 通知类型
type NotifyType int32

const (
	NotifyType_NOTIFY_TYPE_UNKNOWN NotifyType = 0
	NotifyType_LIKE_FAVORITE       NotifyType = 10 // 赞或收藏 按内容聚合
	NotifyType_COMMENT_REPLY       NotifyType = 20 // 评论或回复 单条
	NotifyType_FOLLOW              NotifyType = 30 // 关注 单条
)

// Enum value maps for NotifyType.
var (
	NotifyType_name = map[int32]string{
		0:  "NOTIFY_TYPE_UNKNOWN",
		10: "LIKE_FAVORITE",
		20: "COMMENT_REPLY",
		30: "FOLLOW",
	}
	NotifyType_value = map[string]int32{
		"NOTIFY_TYPE_UNKNOWN": 0,
		"LIKE_FAVORITE":       10,
		"COMMENT_REPLY":       20,
		"FOLLOW":              30,
	}
)

func (x NotifyType) Enum() *NotifyType {
	p := new(NotifyType)
	*p = x
	return p
}

func (x NotifyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_rpc_notification_proto_notification_proto_enumTypes[0].Descriptor()
}

func (NotifyType) Type() protoreflect.EnumType {
	return &file_app_rpc_notification_proto_notification_proto_enumTypes[0]
}

func (x NotifyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyType.Descriptor instead.
func (NotifyType) EnumDescriptor() ([]byte, []int) {
	return file_app_rpc_notification_proto_notification_proto_rawDescGZIP(), []int{0}
}

// NotificationItem 通知原始行 富化在 front BFF 完成
type NotificationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RecipientId   int64                  `protobuf:"varint,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	ActorId       int64                  `protobuf:"varint,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	NotifyType    NotifyType             `protobuf:"varint,4,opt,name=notify_type,json=notifyType,proto3,enum=notification.NotifyType" json:"notify_type,omitempty"`
	AggCount      int64                  `protobuf:"varint,5,opt,name=agg_count,json=aggCount,proto3" json:"agg_count,omitempty"`
	ContentId     int64                  `protobuf:"varint,6,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	CommentId     int64                  `protobuf:"varint,7,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Snippet       string                 `protobuf:"bytes,8,opt,name=snippet,proto3" json:"snippet,omitempty"`
	IsRead        bool                   `protobuf:"varint,9,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 毫秒时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationItem) Reset() {
	*x = NotificationItem{}
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationItem) ProtoMessage() {}

func (x *NotificationItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationItem.ProtoReflect.Descriptor instead.
func (*NotificationItem) Descriptor() ([]byte, []int) {
	return file_app_rpc_notification_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationItem) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *NotificationItem) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *NotificationItem) GetNotifyType() NotifyType {
	if x != nil {
		return x.NotifyType
	}
	return NotifyType_NOTIFY_TYPE_UNKNOWN
}

func (x *NotificationItem) GetAggCount() int64 {
	if x != nil {
		return x.AggCount
	}
	return 0
}

func (x *NotificationItem) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *NotificationItem) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *NotificationItem) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *NotificationItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ListNotificationsReq 收件箱列表 updated_at,id 复合游标
type ListNotificationsReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecipientId     int64                  `protobuf:"varint,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	CursorUpdatedAt int64                  `protobuf:"varint,2,opt,name=cursor_updated_at,json=cursorUpdatedAt,proto3" json:"cursor_updated_at,omitempty"` // 0 表示首页
	CursorId        int64                  `protobuf:"varint,3,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`
	PageSize        uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TypeFilter      NotifyType             `protobuf:"varint,5,opt,name=type_filter,json=typeFilter,proto3,enum=notification.NotifyType" json:"type_filter,omitempty"` // NOTIFY_TYPE_UNKNOWN 表示全部
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListNotificationsReq) Reset() {
	*x = ListNotificationsReq{}
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsReq) ProtoMessage() {}

func (x *ListNotificationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsReq.ProtoReflect.Descriptor instead.
func (*ListNotificationsReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_notification_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsReq) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *ListNotificationsReq) GetCursorUpdatedAt() int64 {
	if x != nil {
		return x.CursorUpdatedAt
	}
	return 0
}

func (x *ListNotificationsReq) GetCursorId() int64 {
	if x != nil {
		return x.CursorId
	}
	return 0
}

func (x *ListNotificationsReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotificationsReq) GetTypeFilter() NotifyType {
	if x != nil {
		return x.TypeFilter
	}
	return NotifyType_NOTIFY_TYPE_UNKNOWN
}

// ListNotificationsRes 列表结果
type ListNotificationsRes struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Items               []*NotificationItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursorUpdatedAt int64                  `protobuf:"varint,2,opt,name=next_cursor_updated_at,json=nextCursorUpdatedAt,proto3" json:"next_cursor_updated_at,omitempty"`
	NextCursorId        int64                  `protobuf:"varint,3,opt,name=next_cursor_id,json=nextCursorId,proto3" json:"next_cursor_id,omitempty"`
	HasMore             bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListNotificationsRes) Reset() {
	*x = ListNotificationsRes{}
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRes) ProtoMessage() {}

func (x *ListNotificationsRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRes.ProtoReflect.Descriptor instead.
func (*ListNotificationsRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_notification_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ListNotificationsRes) GetItems() []*NotificationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListNotificationsRes) GetNextCursorUpdatedAt() int64 {
	if x != nil {
		return x.NextCursorUpdatedAt
	}
	return 0
}

func (x *ListNotificationsRes) GetNextCursorId() int64 {
	if x != nil {
		return x.NextCursorId
	}
	return 0
}

func (x *ListNotificationsRes) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// GetUnreadCountReq 查询未读数
type GetUnreadCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   int64                  `protobuf:"varint,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountReq) Reset() {
	*x = GetUnreadCountReq{}
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountReq) ProtoMessage() {}

func (x *GetUnreadCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountReq.ProtoReflect.Descriptor instead.
func (*GetUnreadCountReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_notification_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetUnreadCountReq) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

// GetUnreadCountRes 未读数结果
type GetUnreadCountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRes) Reset() {
	*x = GetUnreadCountRes{}
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRes) ProtoMessage() {}

func (x *GetUnreadCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRes.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_notification_proto_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetUnreadCountRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// MarkReadReq 按 id 标已读 recipient_id 限定作用域防越权
type MarkReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   int64                  `protobuf:"varint,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Ids           []int64                `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadReq) Reset() {
	*x = MarkReadReq{}
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadReq) ProtoMessage() {}

func (x *MarkReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadReq.ProtoReflect.Descriptor instead.
func (*MarkReadReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_notification_proto_notification_proto_rawDescGZIP(), []int{5}
}

func (x *MarkReadReq) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *MarkReadReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// MarkReadRes 标已读结果
type MarkReadRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Affected      int64                  `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadRes) Reset() {
	*x = MarkReadRes{}
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRes) ProtoMessage() {}

func (x *MarkReadRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRes.ProtoReflect.Descriptor instead.
func (*MarkReadRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_notification_proto_notification_proto_rawDescGZIP(), []int{6}
}

func (x *MarkReadRes) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

// MarkAllReadReq 全部标已读
type MarkAllReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   int64                  `protobuf:"varint,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadReq) Reset() {
	*x = MarkAllReadReq{}
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadReq) ProtoMessage() {}

func (x *MarkAllReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadReq.ProtoReflect.Descriptor instead.
func (*MarkAllReadReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_notification_proto_notification_proto_rawDescGZIP(), []int{7}
}

func (x *MarkAllReadReq) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

// MarkAllReadRes 全部标已读结果
type MarkAllReadRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Affected      int64                  `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadRes) Reset() {
	*x = MarkAllReadRes{}
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadRes) ProtoMessage() {}

func (x *MarkAllReadRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_notification_proto_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadRes.ProtoReflect.Descriptor instead.
func (*MarkAllReadRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_notification_proto_notification_proto_rawDescGZIP(), []int{8}
}

func (x *MarkAllReadRes) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

var File_app_rpc_notification_proto_notification_proto protoreflect.FileDescriptor

const file_app_rpc_notification_proto_notification_proto_rawDesc = "" +
	"\n" +
	"-app/rpc/notification/proto/notification.proto\x12\fnotification\"\xc8\x02\n" +
	"\x10NotificationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\x03R\vrecipientId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\x03R\aactorId\x129\n" +
	"\vnotify_type\x18\x04 \x01(\x0e2\x18.notification.NotifyTypeR\n" +
	"notifyType\x12\x1b\n" +
	"\tagg_count\x18\x05 \x01(\x03R\baggCount\x12\x1d\n" +
	"\n" +
	"content_id\x18\x06 \x01(\x03R\tcontentId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\a \x01(\x03R\tcommentId\x12\x18\n" +
	"\asnippet\x18\b \x01(\tR\asnippet\x12\x17\n" +
	"\ais_read\x18\t \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"\xda\x01\n" +
	"\x14ListNotificationsReq\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\x03R\vrecipientId\x12*\n" +
	"\x11cursor_updated_at\x18\x02 \x01(\x03R\x0fcursorUpdatedAt\x12\x1b\n" +
	"\tcursor_id\x18\x03 \x01(\x03R\bcursorId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\x129\n" +
	"\vtype_filter\x18\x05 \x01(\x0e2\x18.notification.NotifyTypeR\n" +
	"typeFilter\"\xc2\x01\n" +
	"\x14ListNotificationsRes\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.notification.NotificationItemR\x05items\x123\n" +
	"\x16next_cursor_updated_at\x18\x02 \x01(\x03R\x13nextCursorUpdatedAt\x12$\n" +
	"\x0enext_cursor_id\x18\x03 \x01(\x03R\fnextCursorId\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"6\n" +
	"\x11GetUnreadCountReq\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\x03R\vrecipientId\")\n" +
	"\x11GetUnreadCountRes\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\"B\n" +
	"\vMarkReadReq\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\x03R\vrecipientId\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\x03R\x03ids\")\n" +
	"\vMarkReadRes\x12\x1a\n" +
	"\baffected\x18\x01 \x01(\x03R\baffected\"3\n" +
	"\x0eMarkAllReadReq\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\x03R\vrecipientId\",\n" +
	"\x0eMarkAllReadRes\x12\x1a\n" +
	"\baffected\x18\x01 \x01(\x03R\baffected*W\n" +
	"\n" +
	"NotifyType\x12\x17\n" +
	"\x13NOTIFY_TYPE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rLIKE_FAVORITE\x10\n" +
	"\x12\x11\n" +
	"\rCOMMENT_REPLY\x10\x14\x12\n" +
	"\n" +
	"\x06FOLLOW\x10\x1e2\xd3\x02\n" +
	"\x13NotificationService\x12[\n" +
	"\x11ListNotifications\x12\".notification.ListNotificationsReq\x1a\".notification.ListNotificationsRes\x12R\n" +
	"\x0eGetUnreadCount\x12\x1f.notification.GetUnreadCountReq\x1a\x1f.notification.GetUnreadCountRes\x12@\n" +
	"\bMarkRead\x12\x19.notification.MarkReadReq\x1a\x19.notification.MarkReadRes\x12I\n" +
	"\vMarkAllRead\x12\x1c.notification.MarkAllReadReq\x1a\x1c.notification.MarkAllReadResB\x10Z\x0e./notificationb\x06proto3"

var (
	file_app_rpc_notification_proto_notification_proto_rawDescOnce sync.Once
	file_app_rpc_notification_proto_notification_proto_rawDescData []byte
)

func file_app_rpc_notification_proto_notification_proto_rawDescGZIP() []byte {
	file_app_rpc_notification_proto_notification_proto_rawDescOnce.Do(func() {
		file_app_rpc_notification_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_rpc_notification_proto_notification_proto_rawDesc), len(file_app_rpc_notification_proto_notification_proto_rawDesc)))
	})
	return file_app_rpc_notification_proto_notification_proto_rawDescData
}

var file_app_rpc_notification_proto_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_rpc_notification_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_app_rpc_notification_proto_notification_proto_goTypes = []any{
	(NotifyType)(0),              // 0: notification.NotifyType
	(*NotificationItem)(nil),     // 1: notification.NotificationItem
	(*ListNotificationsReq)(nil), // 2: notification.ListNotificationsReq
	(*ListNotificationsRes)(nil), // 3: notification.ListNotificationsRes
	(*GetUnreadCountReq)(nil),    // 4: notification.GetUnreadCountReq
	(*GetUnreadCountRes)(nil),    // 5: notification.GetUnreadCountRes
	(*MarkReadReq)(nil),          // 6: notification.MarkReadReq
	(*MarkReadRes)(nil),          // 7: notification.MarkReadRes
	(*MarkAllReadReq)(nil),       // 8: notification.MarkAllReadReq
	(*MarkAllReadRes)(nil),       // 9: notification.MarkAllReadRes
}
var file_app_rpc_notification_proto_notification_proto_depIdxs = []int32{
	0, // 0: notification.NotificationItem.notify_type:type_name -> notification.NotifyType
	0, // 1: notification.ListNotificationsReq.type_filter:type_name -> notification.NotifyType
	1, // 2: notification.ListNotificationsRes.items:type_name -> notification.NotificationItem
	2, // 3: notification.NotificationService.ListNotifications:input_type -> notification.ListNotificationsReq
	4, // 4: notification.NotificationService.GetUnreadCount:input_type -> notification.GetUnreadCountReq
	6, // 5: notification.NotificationService.MarkRead:input_type -> notification.MarkReadReq
	8, // 6: notification.NotificationService.MarkAllRead:input_type -> notification.MarkAllReadReq
	3, // 7: notification.NotificationService.ListNotifications:output_type -> notification.ListNotificationsRes
	5, // 8: notification.NotificationService.GetUnreadCount:output_type -> notification.GetUnreadCountRes
	7, // 9: notification.NotificationService.MarkRead:output_type -> notification.MarkReadRes
	9, // 10: notification.NotificationService.MarkAllRead:output_type -> notification.MarkAllReadRes
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_rpc_notification_proto_notification_proto_init() }
func file_app_rpc_notification_proto_notification_proto_init() {
	if File_app_rpc_notification_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_rpc_notification_proto_notification_proto_rawDesc), len(file_app_rpc_notification_proto_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_rpc_notification_proto_notification_proto_goTypes,
		DependencyIndexes: file_app_rpc_notification_proto_notification_proto_depIdxs,
		EnumInfos:         file_app_rpc_notification_proto_notification_proto_enumTypes,
		MessageInfos:      file_app_rpc_notification_proto_notification_proto_msgTypes,
	}.Build()
	File_app_rpc_notification_proto_notification_proto = out.File
	file_app_rpc_notification_proto_notification_proto_goTypes = nil
	file_app_rpc_notification_proto_notification_proto_depIdxs = nil
}
