// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: app/rpc/admin/proto/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	commonpb "ran-feed/pkg/commonpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdminStatus 管理员账号状态
type AdminStatus int32

const (
	AdminStatus_ADMIN_STATUS_UNSPECIFIED AdminStatus = 0
	AdminStatus_ADMIN_STATUS_ENABLED     AdminStatus = 10
	AdminStatus_ADMIN_STATUS_DISABLED    AdminStatus = 20
)

// Enum value maps for AdminStatus.
var (
	AdminStatus_name = map[int32]string{
		0:  "ADMIN_STATUS_UNSPECIFIED",
		10: "ADMIN_STATUS_ENABLED",
		20: "ADMIN_STATUS_DISABLED",
	}
	AdminStatus_value = map[string]int32{
		"ADMIN_STATUS_UNSPECIFIED": 0,
		"ADMIN_STATUS_ENABLED":     10,
		"ADMIN_STATUS_DISABLED":    20,
	}
)

func (x AdminStatus) Enum() *AdminStatus {
	p := new(AdminStatus)
	*p = x
	return p
}

func (x AdminStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_app_rpc_admin_proto_admin_proto_enumTypes[0].Descriptor()
}

func (AdminStatus) Type() protoreflect.EnumType {
	return &file_app_rpc_admin_proto_admin_proto_enumTypes[0]
}

func (x AdminStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminStatus.Descriptor instead.
func (AdminStatus) EnumDescriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{0}
}

// AuthenticateAdminReq 校验管理员账号密码
type AuthenticateAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateAdminReq) Reset() {
	*x = AuthenticateAdminReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateAdminReq) ProtoMessage() {}

func (x *AuthenticateAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateAdminReq.ProtoReflect.Descriptor instead.
func (*AuthenticateAdminReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateAdminReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateAdminReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// AuthenticateAdminRes 校验结果
type AuthenticateAdminRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Status        *commonpb.EnumValue    `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateAdminRes) Reset() {
	*x = AuthenticateAdminRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateAdminRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateAdminRes) ProtoMessage() {}

func (x *AuthenticateAdminRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateAdminRes.ProtoReflect.Descriptor instead.
func (*AuthenticateAdminRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateAdminRes) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *AuthenticateAdminRes) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AuthenticateAdminRes) GetStatus() *commonpb.EnumValue {
	if x != nil {
		return x.Status
	}
	return nil
}

// GetAdminReq 查询管理员基本信息
type GetAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminReq) Reset() {
	*x = GetAdminReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminReq) ProtoMessage() {}

func (x *GetAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminReq.ProtoReflect.Descriptor instead.
func (*GetAdminReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdminReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

// GetAdminRes 管理员基本信息
type GetAdminRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Status        *commonpb.EnumValue    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRes) Reset() {
	*x = GetAdminRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRes) ProtoMessage() {}

func (x *GetAdminRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRes.ProtoReflect.Descriptor instead.
func (*GetAdminRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdminRes) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *GetAdminRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetAdminRes) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetAdminRes) GetStatus() *commonpb.EnumValue {
	if x != nil {
		return x.Status
	}
	return nil
}

// ListAdminPermissionsReq 查询管理员权限点集合
type ListAdminPermissionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminPermissionsReq) Reset() {
	*x = ListAdminPermissionsReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminPermissionsReq) ProtoMessage() {}

func (x *ListAdminPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminPermissionsReq.ProtoReflect.Descriptor instead.
func (*ListAdminPermissionsReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListAdminPermissionsReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

// ListAdminPermissionsRes 权限点 code 集合
type ListAdminPermissionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminPermissionsRes) Reset() {
	*x = ListAdminPermissionsRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminPermissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminPermissionsRes) ProtoMessage() {}

func (x *ListAdminPermissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminPermissionsRes.ProtoReflect.Descriptor instead.
func (*ListAdminPermissionsRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListAdminPermissionsRes) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

// WriteOperationLogReq 写操作审计日志
type WriteOperationLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	Ip            string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOperationLogReq) Reset() {
	*x = WriteOperationLogReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOperationLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOperationLogReq) ProtoMessage() {}

func (x *WriteOperationLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOperationLogReq.ProtoReflect.Descriptor instead.
func (*WriteOperationLogReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *WriteOperationLogReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *WriteOperationLogReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WriteOperationLogReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *WriteOperationLogReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *WriteOperationLogReq) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *WriteOperationLogReq) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *WriteOperationLogReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// WriteOperationLogRes 写入结果
type WriteOperationLogRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOperationLogRes) Reset() {
	*x = WriteOperationLogRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOperationLogRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOperationLogRes) ProtoMessage() {}

func (x *WriteOperationLogRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOperationLogRes.ProtoReflect.Descriptor instead.
func (*WriteOperationLogRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *WriteOperationLogRes) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

// PermissionItem 权限点目录项
type PermissionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Module        string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionItem) Reset() {
	*x = PermissionItem{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionItem) ProtoMessage() {}

func (x *PermissionItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionItem.ProtoReflect.Descriptor instead.
func (*PermissionItem) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *PermissionItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermissionItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionItem) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

// ListPermissionsReq 查询权限点目录 module 空则全量
type ListPermissionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsReq) Reset() {
	*x = ListPermissionsReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsReq) ProtoMessage() {}

func (x *ListPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsReq.ProtoReflect.Descriptor instead.
func (*ListPermissionsReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListPermissionsReq) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

// ListPermissionsRes 权限点目录
type ListPermissionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PermissionItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRes) Reset() {
	*x = ListPermissionsRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRes) ProtoMessage() {}

func (x *ListPermissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRes.ProtoReflect.Descriptor instead.
func (*ListPermissionsRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ListPermissionsRes) GetItems() []*PermissionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// OperationLogItem 操作审计日志项
type OperationLogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	TargetType    string                 `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	Ip            string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLogItem) Reset() {
	*x = OperationLogItem{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLogItem) ProtoMessage() {}

func (x *OperationLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLogItem.ProtoReflect.Descriptor instead.
func (*OperationLogItem) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{11}
}

func (x *OperationLogItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperationLogItem) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *OperationLogItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *OperationLogItem) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *OperationLogItem) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *OperationLogItem) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *OperationLogItem) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OperationLogItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListOperationLogsReq 查询操作审计日志 可选筛选加分页
type ListOperationLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Page          uint32                 `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationLogsReq) Reset() {
	*x = ListOperationLogsReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationLogsReq) ProtoMessage() {}

func (x *ListOperationLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationLogsReq.ProtoReflect.Descriptor instead.
func (*ListOperationLogsReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ListOperationLogsReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *ListOperationLogsReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListOperationLogsReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ListOperationLogsReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListOperationLogsReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListOperationLogsReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOperationLogsReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListOperationLogsRes 审计日志分页结果
type ListOperationLogsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OperationLogItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationLogsRes) Reset() {
	*x = ListOperationLogsRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationLogsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationLogsRes) ProtoMessage() {}

func (x *ListOperationLogsRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationLogsRes.ProtoReflect.Descriptor instead.
func (*ListOperationLogsRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ListOperationLogsRes) GetItems() []*OperationLogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListOperationLogsRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOperationLogsRes) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOperationLogsRes) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// RoleItem 角色项
type RoleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleItem) Reset() {
	*x = RoleItem{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleItem) ProtoMessage() {}

func (x *RoleItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleItem.ProtoReflect.Descriptor instead.
func (*RoleItem) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{14}
}

func (x *RoleItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RoleItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListRolesReq 角色分页
type ListRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesReq) Reset() {
	*x = ListRolesReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesReq) ProtoMessage() {}

func (x *ListRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesReq.ProtoReflect.Descriptor instead.
func (*ListRolesReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ListRolesReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListRolesRes 角色分页结果
type ListRolesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RoleItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRes) Reset() {
	*x = ListRolesRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRes) ProtoMessage() {}

func (x *ListRolesRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRes.ProtoReflect.Descriptor instead.
func (*ListRolesRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{16}
}

func (x *ListRolesRes) GetItems() []*RoleItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListRolesRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRolesRes) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesRes) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetRoleDetailReq 角色详情
type GetRoleDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleDetailReq) Reset() {
	*x = GetRoleDetailReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleDetailReq) ProtoMessage() {}

func (x *GetRoleDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleDetailReq.ProtoReflect.Descriptor instead.
func (*GetRoleDetailReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{17}
}

func (x *GetRoleDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetRoleDetailRes 角色详情含所绑权限点ID集合
type GetRoleDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleItem              `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	PermissionIds []int64                `protobuf:"varint,2,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleDetailRes) Reset() {
	*x = GetRoleDetailRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleDetailRes) ProtoMessage() {}

func (x *GetRoleDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleDetailRes.ProtoReflect.Descriptor instead.
func (*GetRoleDetailRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{18}
}

func (x *GetRoleDetailRes) GetRole() *RoleItem {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *GetRoleDetailRes) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

// CreateRoleReq 建角色 code 唯一
type CreateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	OperatorId    int64                  `protobuf:"varint,4,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{19}
}

func (x *CreateRoleReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreateRoleReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// CreateRoleRes 建角色结果
type CreateRoleRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRes) Reset() {
	*x = CreateRoleRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRes) ProtoMessage() {}

func (x *CreateRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRes.ProtoReflect.Descriptor instead.
func (*CreateRoleRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{20}
}

func (x *CreateRoleRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// UpdateRoleReq 改角色 不可改 code
type UpdateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	OperatorId    int64                  `protobuf:"varint,4,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateRoleReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// SetRolePermissionsReq 覆盖式设角色权限点
type SetRolePermissionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionIds []int64                `protobuf:"varint,2,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	OperatorId    int64                  `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRolePermissionsReq) Reset() {
	*x = SetRolePermissionsReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRolePermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRolePermissionsReq) ProtoMessage() {}

func (x *SetRolePermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRolePermissionsReq.ProtoReflect.Descriptor instead.
func (*SetRolePermissionsReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{22}
}

func (x *SetRolePermissionsReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *SetRolePermissionsReq) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

func (x *SetRolePermissionsReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// SetRolePermissionsRes 返回受影响管理员ID供上层失效权限缓存
type SetRolePermissionsRes struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AffectedAdminIds []int64                `protobuf:"varint,1,rep,packed,name=affected_admin_ids,json=affectedAdminIds,proto3" json:"affected_admin_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetRolePermissionsRes) Reset() {
	*x = SetRolePermissionsRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRolePermissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRolePermissionsRes) ProtoMessage() {}

func (x *SetRolePermissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRolePermissionsRes.ProtoReflect.Descriptor instead.
func (*SetRolePermissionsRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{23}
}

func (x *SetRolePermissionsRes) GetAffectedAdminIds() []int64 {
	if x != nil {
		return x.AffectedAdminIds
	}
	return nil
}

// DeleteRoleReq 删角色
type DeleteRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleReq) Reset() {
	*x = DeleteRoleReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleReq) ProtoMessage() {}

func (x *DeleteRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleReq.ProtoReflect.Descriptor instead.
func (*DeleteRoleReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteRoleReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// DeleteRoleRes 返回受影响管理员ID供上层失效权限缓存
type DeleteRoleRes struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AffectedAdminIds []int64                `protobuf:"varint,1,rep,packed,name=affected_admin_ids,json=affectedAdminIds,proto3" json:"affected_admin_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteRoleRes) Reset() {
	*x = DeleteRoleRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRes) ProtoMessage() {}

func (x *DeleteRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRes.ProtoReflect.Descriptor instead.
func (*DeleteRoleRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteRoleRes) GetAffectedAdminIds() []int64 {
	if x != nil {
		return x.AffectedAdminIds
	}
	return nil
}

// AdminListItem 管理员信息
type AdminListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Status        *commonpb.EnumValue    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	RoleCodes     []string               `protobuf:"bytes,5,rep,name=role_codes,json=roleCodes,proto3" json:"role_codes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListItem) Reset() {
	*x = AdminListItem{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListItem) ProtoMessage() {}

func (x *AdminListItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListItem.ProtoReflect.Descriptor instead.
func (*AdminListItem) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{26}
}

func (x *AdminListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminListItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminListItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminListItem) GetStatus() *commonpb.EnumValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AdminListItem) GetRoleCodes() []string {
	if x != nil {
		return x.RoleCodes
	}
	return nil
}

func (x *AdminListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListAdminsReq 管理员分页查询 status 为空查全部
type ListAdminsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AdminStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=ranfeed.admin.AdminStatus" json:"status,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminsReq) Reset() {
	*x = ListAdminsReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminsReq) ProtoMessage() {}

func (x *ListAdminsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminsReq.ProtoReflect.Descriptor instead.
func (*ListAdminsReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{27}
}

func (x *ListAdminsReq) GetStatus() AdminStatus {
	if x != nil {
		return x.Status
	}
	return AdminStatus_ADMIN_STATUS_UNSPECIFIED
}

func (x *ListAdminsReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdminsReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListAdminsRes 管理员分页查询结果
type ListAdminsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AdminListItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminsRes) Reset() {
	*x = ListAdminsRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminsRes) ProtoMessage() {}

func (x *ListAdminsRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminsRes.ProtoReflect.Descriptor instead.
func (*ListAdminsRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{28}
}

func (x *ListAdminsRes) GetItems() []*AdminListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAdminsRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAdminsRes) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdminsRes) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetAdminDetailReq 管理员详情
type GetAdminDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminDetailReq) Reset() {
	*x = GetAdminDetailReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminDetailReq) ProtoMessage() {}

func (x *GetAdminDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminDetailReq.ProtoReflect.Descriptor instead.
func (*GetAdminDetailReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{29}
}

func (x *GetAdminDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetAdminDetailRes 管理员详情含所绑角色ID集合
type GetAdminDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *AdminListItem         `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	RoleIds       []int64                `protobuf:"varint,2,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminDetailRes) Reset() {
	*x = GetAdminDetailRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminDetailRes) ProtoMessage() {}

func (x *GetAdminDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminDetailRes.ProtoReflect.Descriptor instead.
func (*GetAdminDetailRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{30}
}

func (x *GetAdminDetailRes) GetAdmin() *AdminListItem {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *GetAdminDetailRes) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// CreateAdminReq 创建管理员
type CreateAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RoleIds       []int64                `protobuf:"varint,4,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	OperatorId    int64                  `protobuf:"varint,5,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminReq) Reset() {
	*x = CreateAdminReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminReq) ProtoMessage() {}

func (x *CreateAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminReq.ProtoReflect.Descriptor instead.
func (*CreateAdminReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{31}
}

func (x *CreateAdminReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAdminReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAdminReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateAdminReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *CreateAdminReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// CreateAdminRes 建管理员结果
type CreateAdminRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRes) Reset() {
	*x = CreateAdminRes{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRes) ProtoMessage() {}

func (x *CreateAdminRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRes.ProtoReflect.Descriptor instead.
func (*CreateAdminRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{32}
}

func (x *CreateAdminRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// UpdateAdminReq 修改管理员昵称
type UpdateAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	OperatorId    int64                  `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminReq) Reset() {
	*x = UpdateAdminReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminReq) ProtoMessage() {}

func (x *UpdateAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminReq.ProtoReflect.Descriptor instead.
func (*UpdateAdminReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateAdminReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAdminReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateAdminReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// SetAdminStatusReq 启用禁用管理员
type SetAdminStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        AdminStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=ranfeed.admin.AdminStatus" json:"status,omitempty"`
	OperatorId    int64                  `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminStatusReq) Reset() {
	*x = SetAdminStatusReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminStatusReq) ProtoMessage() {}

func (x *SetAdminStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminStatusReq.ProtoReflect.Descriptor instead.
func (*SetAdminStatusReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{34}
}

func (x *SetAdminStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetAdminStatusReq) GetStatus() AdminStatus {
	if x != nil {
		return x.Status
	}
	return AdminStatus_ADMIN_STATUS_UNSPECIFIED
}

func (x *SetAdminStatusReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// ResetAdminPasswordReq 重置管理员密码
type ResetAdminPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	OperatorId    int64                  `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAdminPasswordReq) Reset() {
	*x = ResetAdminPasswordReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAdminPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAdminPasswordReq) ProtoMessage() {}

func (x *ResetAdminPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAdminPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetAdminPasswordReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{35}
}

func (x *ResetAdminPasswordReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResetAdminPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ResetAdminPasswordReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// SetAdminRolesReq 设置管理员角色
type SetAdminRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	RoleIds       []int64                `protobuf:"varint,2,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	OperatorId    int64                  `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminRolesReq) Reset() {
	*x = SetAdminRolesReq{}
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminRolesReq) ProtoMessage() {}

func (x *SetAdminRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_admin_proto_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminRolesReq.ProtoReflect.Descriptor instead.
func (*SetAdminRolesReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_admin_proto_admin_proto_rawDescGZIP(), []int{36}
}

func (x *SetAdminRolesReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *SetAdminRolesReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *SetAdminRolesReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

var File_app_rpc_admin_proto_admin_proto protoreflect.FileDescriptor

const file_app_rpc_admin_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x1fapp/rpc/admin/proto/admin.proto\x12\rranfeed.admin\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19pkg/commonpb/common.proto\"N\n" +
	"\x14AuthenticateAdminReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x82\x01\n" +
	"\x14AuthenticateAdminRes\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x123\n" +
	"\x06status\x18\x03 \x01(\v2\x1b.ranfeed.commonpb.EnumValueR\x06status\"(\n" +
	"\vGetAdminReq\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\"\x95\x01\n" +
	"\vGetAdminRes\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x123\n" +
	"\x06status\x18\x04 \x01(\v2\x1b.ranfeed.commonpb.EnumValueR\x06status\"4\n" +
	"\x17ListAdminPermissionsReq\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\"/\n" +
	"\x17ListAdminPermissionsRes\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"\xc9\x01\n" +
	"\x14WriteOperationLogReq\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x03R\btargetId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\"-\n" +
	"\x14WriteOperationLogRes\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\"`\n" +
	"\x0ePermissionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06module\x18\x04 \x01(\tR\x06module\",\n" +
	"\x12ListPermissionsReq\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\"I\n" +
	"\x12ListPermissionsRes\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.ranfeed.admin.PermissionItemR\x05items\"\xf6\x01\n" +
	"\x10OperationLogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x04 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8d\x02\n" +
	"\x14ListOperationLogsReq\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x12\n" +
	"\x04page\x18\x06 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\rR\bpageSize\"\x94\x01\n" +
	"\x14ListOperationLogsRes\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.ranfeed.admin.OperationLogItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"\x95\x01\n" +
	"\bRoleItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"?\n" +
	"\fListRolesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"\x84\x01\n" +
	"\fListRolesRes\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.ranfeed.admin.RoleItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"\"\n" +
	"\x10GetRoleDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"f\n" +
	"\x10GetRoleDetailRes\x12+\n" +
	"\x04role\x18\x01 \x01(\v2\x17.ranfeed.admin.RoleItemR\x04role\x12%\n" +
	"\x0epermission_ids\x18\x02 \x03(\x03R\rpermissionIds\"p\n" +
	"\rCreateRoleReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x1f\n" +
	"\voperator_id\x18\x04 \x01(\x03R\n" +
	"operatorId\"\x1f\n" +
	"\rCreateRoleRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"l\n" +
	"\rUpdateRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x1f\n" +
	"\voperator_id\x18\x04 \x01(\x03R\n" +
	"operatorId\"x\n" +
	"\x15SetRolePermissionsReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12%\n" +
	"\x0epermission_ids\x18\x02 \x03(\x03R\rpermissionIds\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x03R\n" +
	"operatorId\"E\n" +
	"\x15SetRolePermissionsRes\x12,\n" +
	"\x12affected_admin_ids\x18\x01 \x03(\x03R\x10affectedAdminIds\"@\n" +
	"\rDeleteRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\"=\n" +
	"\rDeleteRoleRes\x12,\n" +
	"\x12affected_admin_ids\x18\x01 \x03(\x03R\x10affectedAdminIds\"\xe6\x01\n" +
	"\rAdminListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x123\n" +
	"\x06status\x18\x04 \x01(\v2\x1b.ranfeed.commonpb.EnumValueR\x06status\x12\x1d\n" +
	"\n" +
	"role_codes\x18\x05 \x03(\tR\troleCodes\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"t\n" +
	"\rListAdminsReq\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.ranfeed.admin.AdminStatusR\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"\x8a\x01\n" +
	"\rListAdminsRes\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.ranfeed.admin.AdminListItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"#\n" +
	"\x11GetAdminDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"b\n" +
	"\x11GetAdminDetailRes\x122\n" +
	"\x05admin\x18\x01 \x01(\v2\x1c.ranfeed.admin.AdminListItemR\x05admin\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\x03R\aroleIds\"\xa0\x01\n" +
	"\x0eCreateAdminReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x19\n" +
	"\brole_ids\x18\x04 \x03(\x03R\aroleIds\x12\x1f\n" +
	"\voperator_id\x18\x05 \x01(\x03R\n" +
	"operatorId\" \n" +
	"\x0eCreateAdminRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"]\n" +
	"\x0eUpdateAdminReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x03R\n" +
	"operatorId\"x\n" +
	"\x11SetAdminStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.ranfeed.admin.AdminStatusR\x06status\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x03R\n" +
	"operatorId\"k\n" +
	"\x15ResetAdminPasswordReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x03R\n" +
	"operatorId\"i\n" +
	"\x10SetAdminRolesReq\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\x03R\aroleIds\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x03R\n" +
	"operatorId*`\n" +
	"\vAdminStatus\x12\x1c\n" +
	"\x18ADMIN_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ADMIN_STATUS_ENABLED\x10\n" +
	"\x12\x19\n" +
	"\x15ADMIN_STATUS_DISABLED\x10\x142\x9d\x02\n" +
	"\x10AdminAuthService\x12]\n" +
	"\x11AuthenticateAdmin\x12#.ranfeed.admin.AuthenticateAdminReq\x1a#.ranfeed.admin.AuthenticateAdminRes\x12B\n" +
	"\bGetAdmin\x12\x1a.ranfeed.admin.GetAdminReq\x1a\x1a.ranfeed.admin.GetAdminRes\x12f\n" +
	"\x14ListAdminPermissions\x12&.ranfeed.admin.ListAdminPermissionsReq\x1a&.ranfeed.admin.ListAdminPermissionsRes2\xd1\x01\n" +
	"\x11AdminAuditService\x12]\n" +
	"\x11WriteOperationLog\x12#.ranfeed.admin.WriteOperationLogReq\x1a#.ranfeed.admin.WriteOperationLogRes\x12]\n" +
	"\x11ListOperationLogs\x12#.ranfeed.admin.ListOperationLogsReq\x1a#.ranfeed.admin.ListOperationLogsRes2q\n" +
	"\x16AdminPermissionService\x12W\n" +
	"\x0fListPermissions\x12!.ranfeed.admin.ListPermissionsReq\x1a!.ranfeed.admin.ListPermissionsRes2\xe6\x03\n" +
	"\x10AdminRoleService\x12E\n" +
	"\tListRoles\x12\x1b.ranfeed.admin.ListRolesReq\x1a\x1b.ranfeed.admin.ListRolesRes\x12Q\n" +
	"\rGetRoleDetail\x12\x1f.ranfeed.admin.GetRoleDetailReq\x1a\x1f.ranfeed.admin.GetRoleDetailRes\x12H\n" +
	"\n" +
	"CreateRole\x12\x1c.ranfeed.admin.CreateRoleReq\x1a\x1c.ranfeed.admin.CreateRoleRes\x12B\n" +
	"\n" +
	"UpdateRole\x12\x1c.ranfeed.admin.UpdateRoleReq\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\x12SetRolePermissions\x12$.ranfeed.admin.SetRolePermissionsReq\x1a$.ranfeed.admin.SetRolePermissionsRes\x12H\n" +
	"\n" +
	"DeleteRole\x12\x1c.ranfeed.admin.DeleteRoleReq\x1a\x1c.ranfeed.admin.DeleteRoleRes2\xaf\x04\n" +
	"\x10AdminUserService\x12H\n" +
	"\n" +
	"ListAdmins\x12\x1c.ranfeed.admin.ListAdminsReq\x1a\x1c.ranfeed.admin.ListAdminsRes\x12T\n" +
	"\x0eGetAdminDetail\x12 .ranfeed.admin.GetAdminDetailReq\x1a .ranfeed.admin.GetAdminDetailRes\x12K\n" +
	"\vCreateAdmin\x12\x1d.ranfeed.admin.CreateAdminReq\x1a\x1d.ranfeed.admin.CreateAdminRes\x12D\n" +
	"\vUpdateAdmin\x12\x1d.ranfeed.admin.UpdateAdminReq\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0eSetAdminStatus\x12 .ranfeed.admin.SetAdminStatusReq\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x12ResetAdminPassword\x12$.ranfeed.admin.ResetAdminPasswordReq\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\rSetAdminRoles\x12\x1f.ranfeed.admin.SetAdminRolesReq\x1a\x16.google.protobuf.EmptyB\x1eZ\x1cran-feed/app/rpc/admin/adminb\x06proto3"

var (
	file_app_rpc_admin_proto_admin_proto_rawDescOnce sync.Once
	file_app_rpc_admin_proto_admin_proto_rawDescData []byte
)

func file_app_rpc_admin_proto_admin_proto_rawDescGZIP() []byte {
	file_app_rpc_admin_proto_admin_proto_rawDescOnce.Do(func() {
		file_app_rpc_admin_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_rpc_admin_proto_admin_proto_rawDesc), len(file_app_rpc_admin_proto_admin_proto_rawDesc)))
	})
	return file_app_rpc_admin_proto_admin_proto_rawDescData
}

var file_app_rpc_admin_proto_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_rpc_admin_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_app_rpc_admin_proto_admin_proto_goTypes = []any{
	(AdminStatus)(0),                // 0: ranfeed.admin.AdminStatus
	(*AuthenticateAdminReq)(nil),    // 1: ranfeed.admin.AuthenticateAdminReq
	(*AuthenticateAdminRes)(nil),    // 2: ranfeed.admin.AuthenticateAdminRes
	(*GetAdminReq)(nil),             // 3: ranfeed.admin.GetAdminReq
	(*GetAdminRes)(nil),             // 4: ranfeed.admin.GetAdminRes
	(*ListAdminPermissionsReq)(nil), // 5: ranfeed.admin.ListAdminPermissionsReq
	(*ListAdminPermissionsRes)(nil), // 6: ranfeed.admin.ListAdminPermissionsRes
	(*WriteOperationLogReq)(nil),    // 7: ranfeed.admin.WriteOperationLogReq
	(*WriteOperationLogRes)(nil),    // 8: ranfeed.admin.WriteOperationLogRes
	(*PermissionItem)(nil),          // 9: ranfeed.admin.PermissionItem
	(*ListPermissionsReq)(nil),      // 10: ranfeed.admin.ListPermissionsReq
	(*ListPermissionsRes)(nil),      // 11: ranfeed.admin.ListPermissionsRes
	(*OperationLogItem)(nil),        // 12: ranfeed.admin.OperationLogItem
	(*ListOperationLogsReq)(nil),    // 13: ranfeed.admin.ListOperationLogsReq
	(*ListOperationLogsRes)(nil),    // 14: ranfeed.admin.ListOperationLogsRes
	(*RoleItem)(nil),                // 15: ranfeed.admin.RoleItem
	(*ListRolesReq)(nil),            // 16: ranfeed.admin.ListRolesReq
	(*ListRolesRes)(nil),            // 17: ranfeed.admin.ListRolesRes
	(*GetRoleDetailReq)(nil),        // 18: ranfeed.admin.GetRoleDetailReq
	(*GetRoleDetailRes)(nil),        // 19: ranfeed.admin.GetRoleDetailRes
	(*CreateRoleReq)(nil),           // 20: ranfeed.admin.CreateRoleReq
	(*CreateRoleRes)(nil),           // 21: ranfeed.admin.CreateRoleRes
	(*UpdateRoleReq)(nil),           // 22: ranfeed.admin.UpdateRoleReq
	(*SetRolePermissionsReq)(nil),   // 23: ranfeed.admin.SetRolePermissionsReq
	(*SetRolePermissionsRes)(nil),   // 24: ranfeed.admin.SetRolePermissionsRes
	(*DeleteRoleReq)(nil),           // 25: ranfeed.admin.DeleteRoleReq
	(*DeleteRoleRes)(nil),           // 26: ranfeed.admin.DeleteRoleRes
	(*AdminListItem)(nil),           // 27: ranfeed.admin.AdminListItem
	(*ListAdminsReq)(nil),           // 28: ranfeed.admin.ListAdminsReq
	(*ListAdminsRes)(nil),           // 29: ranfeed.admin.ListAdminsRes
	(*GetAdminDetailReq)(nil),       // 30: ranfeed.admin.GetAdminDetailReq
	(*GetAdminDetailRes)(nil),       // 31: ranfeed.admin.GetAdminDetailRes
	(*CreateAdminReq)(nil),          // 32: ranfeed.admin.CreateAdminReq
	(*CreateAdminRes)(nil),          // 33: ranfeed.admin.CreateAdminRes
	(*UpdateAdminReq)(nil),          // 34: ranfeed.admin.UpdateAdminReq
	(*SetAdminStatusReq)(nil),       // 35: ranfeed.admin.SetAdminStatusReq
	(*ResetAdminPasswordReq)(nil),   // 36: ranfeed.admin.ResetAdminPasswordReq
	(*SetAdminRolesReq)(nil),        // 37: ranfeed.admin.SetAdminRolesReq
	(*commonpb.EnumValue)(nil),      // 38: ranfeed.commonpb.EnumValue
	(*timestamppb.Timestamp)(nil),   // 39: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 40: google.protobuf.Empty
}
var file_app_rpc_admin_proto_admin_proto_depIdxs = []int32{
	38, // 0: ranfeed.admin.AuthenticateAdminRes.status:type_name -> ranfeed.commonpb.EnumValue
	38, // 1: ranfeed.admin.GetAdminRes.status:type_name -> ranfeed.commonpb.EnumValue
	9,  // 2: ranfeed.admin.ListPermissionsRes.items:type_name -> ranfeed.admin.PermissionItem
	39, // 3: ranfeed.admin.OperationLogItem.created_at:type_name -> google.protobuf.Timestamp
	39, // 4: ranfeed.admin.ListOperationLogsReq.start_time:type_name -> google.protobuf.Timestamp
	39, // 5: ranfeed.admin.ListOperationLogsReq.end_time:type_name -> google.protobuf.Timestamp
	12, // 6: ranfeed.admin.ListOperationLogsRes.items:type_name -> ranfeed.admin.OperationLogItem
	39, // 7: ranfeed.admin.RoleItem.created_at:type_name -> google.protobuf.Timestamp
	15, // 8: ranfeed.admin.ListRolesRes.items:type_name -> ranfeed.admin.RoleItem
	15, // 9: ranfeed.admin.GetRoleDetailRes.role:type_name -> ranfeed.admin.RoleItem
	38, // 10: ranfeed.admin.AdminListItem.status:type_name -> ranfeed.commonpb.EnumValue
	39, // 11: ranfeed.admin.AdminListItem.created_at:type_name -> google.protobuf.Timestamp
	0,  // 12: ranfeed.admin.ListAdminsReq.status:type_name -> ranfeed.admin.AdminStatus
	27, // 13: ranfeed.admin.ListAdminsRes.items:type_name -> ranfeed.admin.AdminListItem
	27, // 14: ranfeed.admin.GetAdminDetailRes.admin:type_name -> ranfeed.admin.AdminListItem
	0,  // 15: ranfeed.admin.SetAdminStatusReq.status:type_name -> ranfeed.admin.AdminStatus
	1,  // 16: ranfeed.admin.AdminAuthService.AuthenticateAdmin:input_type -> ranfeed.admin.AuthenticateAdminReq
	3,  // 17: ranfeed.admin.AdminAuthService.GetAdmin:input_type -> ranfeed.admin.GetAdminReq
	5,  // 18: ranfeed.admin.AdminAuthService.ListAdminPermissions:input_type -> ranfeed.admin.ListAdminPermissionsReq
	7,  // 19: ranfeed.admin.AdminAuditService.WriteOperationLog:input_type -> ranfeed.admin.WriteOperationLogReq
	13, // 20: ranfeed.admin.AdminAuditService.ListOperationLogs:input_type -> ranfeed.admin.ListOperationLogsReq
	10, // 21: ranfeed.admin.AdminPermissionService.ListPermissions:input_type -> ranfeed.admin.ListPermissionsReq
	16, // 22: ranfeed.admin.AdminRoleService.ListRoles:input_type -> ranfeed.admin.ListRolesReq
	18, // 23: ranfeed.admin.AdminRoleService.GetRoleDetail:input_type -> ranfeed.admin.GetRoleDetailReq
	20, // 24: ranfeed.admin.AdminRoleService.CreateRole:input_type -> ranfeed.admin.CreateRoleReq
	22, // 25: ranfeed.admin.AdminRoleService.UpdateRole:input_type -> ranfeed.admin.UpdateRoleReq
	23, // 26: ranfeed.admin.AdminRoleService.SetRolePermissions:input_type -> ranfeed.admin.SetRolePermissionsReq
	25, // 27: ranfeed.admin.AdminRoleService.DeleteRole:input_type -> ranfeed.admin.DeleteRoleReq
	28, // 28: ranfeed.admin.AdminUserService.ListAdmins:input_type -> ranfeed.admin.ListAdminsReq
	30, // 29: ranfeed.admin.AdminUserService.GetAdminDetail:input_type -> ranfeed.admin.GetAdminDetailReq
	32, // 30: ranfeed.admin.AdminUserService.CreateAdmin:input_type -> ranfeed.admin.CreateAdminReq
	34, // 31: ranfeed.admin.AdminUserService.UpdateAdmin:input_type -> ranfeed.admin.UpdateAdminReq
	35, // 32: ranfeed.admin.AdminUserService.SetAdminStatus:input_type -> ranfeed.admin.SetAdminStatusReq
	36, // 33: ranfeed.admin.AdminUserService.ResetAdminPassword:input_type -> ranfeed.admin.ResetAdminPasswordReq
	37, // 34: ranfeed.admin.AdminUserService.SetAdminRoles:input_type -> ranfeed.admin.SetAdminRolesReq
	2,  // 35: ranfeed.admin.AdminAuthService.AuthenticateAdmin:output_type -> ranfeed.admin.AuthenticateAdminRes
	4,  // 36: ranfeed.admin.AdminAuthService.GetAdmin:output_type -> ranfeed.admin.GetAdminRes
	6,  // 37: ranfeed.admin.AdminAuthService.ListAdminPermissions:output_type -> ranfeed.admin.ListAdminPermissionsRes
	8,  // 38: ranfeed.admin.AdminAuditService.WriteOperationLog:output_type -> ranfeed.admin.WriteOperationLogRes
	14, // 39: ranfeed.admin.AdminAuditService.ListOperationLogs:output_type -> ranfeed.admin.ListOperationLogsRes
	11, // 40: ranfeed.admin.AdminPermissionService.ListPermissions:output_type -> ranfeed.admin.ListPermissionsRes
	17, // 41: ranfeed.admin.AdminRoleService.ListRoles:output_type -> ranfeed.admin.ListRolesRes
	19, // 42: ranfeed.admin.AdminRoleService.GetRoleDetail:output_type -> ranfeed.admin.GetRoleDetailRes
	21, // 43: ranfeed.admin.AdminRoleService.CreateRole:output_type -> ranfeed.admin.CreateRoleRes
	40, // 44: ranfeed.admin.AdminRoleService.UpdateRole:output_type -> google.protobuf.Empty
	24, // 45: ranfeed.admin.AdminRoleService.SetRolePermissions:output_type -> ranfeed.admin.SetRolePermissionsRes
	26, // 46: ranfeed.admin.AdminRoleService.DeleteRole:output_type -> ranfeed.admin.DeleteRoleRes
	29, // 47: ranfeed.admin.AdminUserService.ListAdmins:output_type -> ranfeed.admin.ListAdminsRes
	31, // 48: ranfeed.admin.AdminUserService.GetAdminDetail:output_type -> ranfeed.admin.GetAdminDetailRes
	33, // 49: ranfeed.admin.AdminUserService.CreateAdmin:output_type -> ranfeed.admin.CreateAdminRes
	40, // 50: ranfeed.admin.AdminUserService.UpdateAdmin:output_type -> google.protobuf.Empty
	40, // 51: ranfeed.admin.AdminUserService.SetAdminStatus:output_type -> google.protobuf.Empty
	40, // 52: ranfeed.admin.AdminUserService.ResetAdminPassword:output_type -> google.protobuf.Empty
	40, // 53: ranfeed.admin.AdminUserService.SetAdminRoles:output_type -> google.protobuf.Empty
	35, // [35:54] is the sub-list for method output_type
	16, // [16:35] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_app_rpc_admin_proto_admin_proto_init() }
func file_app_rpc_admin_proto_admin_proto_init() {
	if File_app_rpc_admin_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_rpc_admin_proto_admin_proto_rawDesc), len(file_app_rpc_admin_proto_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_app_rpc_admin_proto_admin_proto_goTypes,
		DependencyIndexes: file_app_rpc_admin_proto_admin_proto_depIdxs,
		EnumInfos:         file_app_rpc_admin_proto_admin_proto_enumTypes,
		MessageInfos:      file_app_rpc_admin_proto_admin_proto_msgTypes,
	}.Build()
	File_app_rpc_admin_proto_admin_proto = out.File
	file_app_rpc_admin_proto_admin_proto_goTypes = nil
	file_app_rpc_admin_proto_admin_proto_depIdxs = nil
}
