
canal.instance.mysql.slaveId=1234

canal.instance.gtidon=false

canal.instance.master.address=mysql:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

canal.instance.tsdb.enable=true

canal.instance.dbUsername=ran_feed
canal.instance.dbPassword=123456
canal.instance.connectionCharset=UTF-8

canal.instance.filter.regex=ran-feed\\.(ran_feed_favorite|ran_feed_comment|ran_feed_like|ran_feed_follow|ran_feed_content)

canal.mq.topic=ran-feed-count-canal
canal.mq.partition=0
