// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"ran-feed/app/rpc/user/internal/logic/userservice"
	"ran-feed/app/rpc/user/internal/svc"
	"ran-feed/app/rpc/user/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterRes, error) {
	l := userservicelogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginRes, error) {
	l := userservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) Logout(ctx context.Context, in *user.LogoutReq) (*user.LogoutRes, error) {
	l := userservicelogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *UserServiceServer) GetMe(ctx context.Context, in *user.GetMeReq) (*user.GetMeRes, error) {
	l := userservicelogic.NewGetMeLogic(ctx, s.svcCtx)
	return l.GetMe(in)
}

func (s *UserServiceServer) GetUser(ctx context.Context, in *user.GetUserReq) (*user.GetUserRes, error) {
	l := userservicelogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServiceServer) GetUserProfile(ctx context.Context, in *user.GetUserProfileReq) (*user.GetUserProfileRes, error) {
	l := userservicelogic.NewGetUserProfileLogic(ctx, s.svcCtx)
	return l.GetUserProfile(in)
}

func (s *UserServiceServer) BatchGetUser(ctx context.Context, in *user.BatchGetUserReq) (*user.BatchGetUserRes, error) {
	l := userservicelogic.NewBatchGetUserLogic(ctx, s.svcCtx)
	return l.BatchGetUser(in)
}
