// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ran-feed/app/rpc/content/internal/entity/model"
)

func newRanFeedContent(db *gorm.DB, opts ...gen.DOOption) ranFeedContent {
	_ranFeedContent := ranFeedContent{}

	_ranFeedContent.ranFeedContentDo.UseDB(db, opts...)
	_ranFeedContent.ranFeedContentDo.UseModel(&model.RanFeedContent{})

	tableName := _ranFeedContent.ranFeedContentDo.TableName()
	_ranFeedContent.ALL = field.NewAsterisk(tableName)
	_ranFeedContent.ID = field.NewInt64(tableName, "id")
	_ranFeedContent.UserID = field.NewInt64(tableName, "user_id")
	_ranFeedContent.ContentType = field.NewInt32(tableName, "content_type")
	_ranFeedContent.Status = field.NewInt32(tableName, "status")
	_ranFeedContent.Visibility = field.NewInt32(tableName, "visibility")
	_ranFeedContent.LikeCount = field.NewInt64(tableName, "like_count")
	_ranFeedContent.FavoriteCount = field.NewInt64(tableName, "favorite_count")
	_ranFeedContent.CommentCount = field.NewInt64(tableName, "comment_count")
	_ranFeedContent.HotScore = field.NewFloat64(tableName, "hot_score")
	_ranFeedContent.LastHotScoreAt = field.NewTime(tableName, "last_hot_score_at")
	_ranFeedContent.Version = field.NewInt32(tableName, "version")
	_ranFeedContent.IsDeleted = field.NewInt32(tableName, "is_deleted")
	_ranFeedContent.CreatedBy = field.NewInt64(tableName, "created_by")
	_ranFeedContent.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_ranFeedContent.CreatedAt = field.NewTime(tableName, "created_at")
	_ranFeedContent.PublishedAt = field.NewTime(tableName, "published_at")
	_ranFeedContent.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ranFeedContent.fillFieldMap()

	return _ranFeedContent
}

// ranFeedContent 统一内容主表
type ranFeedContent struct {
	ranFeedContentDo ranFeedContentDo

	ALL            field.Asterisk
	ID             field.Int64   // 内容ID
	UserID         field.Int64   // 发布者（内容作者）
	ContentType    field.Int32   // 内容类型 10=文章 20=视频
	Status         field.Int32   // 状态 10=草稿 20=处理中 30=已发布 40=失败
	Visibility     field.Int32   // 可见性 10=公开 20=私密
	LikeCount      field.Int64   // 点赞数
	FavoriteCount  field.Int64   // 收藏数
	CommentCount   field.Int64   // 评论数
	HotScore       field.Float64 // 热度分
	LastHotScoreAt field.Time    // 热度分最后更新时间
	Version        field.Int32   // 版本号（乐观锁）
	IsDeleted      field.Int32   // 逻辑删除 0=正常 1=删除
	CreatedBy      field.Int64   // 创建人
	UpdatedBy      field.Int64   // 最后修改人
	CreatedAt      field.Time    // 创建时间
	PublishedAt    field.Time    // 发布时间
	UpdatedAt      field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (z ranFeedContent) Table(newTableName string) *ranFeedContent {
	z.ranFeedContentDo.UseTable(newTableName)
	return z.updateTableName(newTableName)
}

func (z ranFeedContent) As(alias string) *ranFeedContent {
	z.ranFeedContentDo.DO = *(z.ranFeedContentDo.As(alias).(*gen.DO))
	return z.updateTableName(alias)
}

func (z *ranFeedContent) updateTableName(table string) *ranFeedContent {
	z.ALL = field.NewAsterisk(table)
	z.ID = field.NewInt64(table, "id")
	z.UserID = field.NewInt64(table, "user_id")
	z.ContentType = field.NewInt32(table, "content_type")
	z.Status = field.NewInt32(table, "status")
	z.Visibility = field.NewInt32(table, "visibility")
	z.LikeCount = field.NewInt64(table, "like_count")
	z.FavoriteCount = field.NewInt64(table, "favorite_count")
	z.CommentCount = field.NewInt64(table, "comment_count")
	z.HotScore = field.NewFloat64(table, "hot_score")
	z.LastHotScoreAt = field.NewTime(table, "last_hot_score_at")
	z.Version = field.NewInt32(table, "version")
	z.IsDeleted = field.NewInt32(table, "is_deleted")
	z.CreatedBy = field.NewInt64(table, "created_by")
	z.UpdatedBy = field.NewInt64(table, "updated_by")
	z.CreatedAt = field.NewTime(table, "created_at")
	z.PublishedAt = field.NewTime(table, "published_at")
	z.UpdatedAt = field.NewTime(table, "updated_at")

	z.fillFieldMap()

	return z
}

func (z *ranFeedContent) WithContext(ctx context.Context) IRanFeedContentDo {
	return z.ranFeedContentDo.WithContext(ctx)
}

func (z ranFeedContent) TableName() string { return z.ranFeedContentDo.TableName() }

func (z ranFeedContent) Alias() string { return z.ranFeedContentDo.Alias() }

func (z ranFeedContent) Columns(cols ...field.Expr) gen.Columns {
	return z.ranFeedContentDo.Columns(cols...)
}

func (z *ranFeedContent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := z.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (z *ranFeedContent) fillFieldMap() {
	z.fieldMap = make(map[string]field.Expr, 17)
	z.fieldMap["id"] = z.ID
	z.fieldMap["user_id"] = z.UserID
	z.fieldMap["content_type"] = z.ContentType
	z.fieldMap["status"] = z.Status
	z.fieldMap["visibility"] = z.Visibility
	z.fieldMap["like_count"] = z.LikeCount
	z.fieldMap["favorite_count"] = z.FavoriteCount
	z.fieldMap["comment_count"] = z.CommentCount
	z.fieldMap["hot_score"] = z.HotScore
	z.fieldMap["last_hot_score_at"] = z.LastHotScoreAt
	z.fieldMap["version"] = z.Version
	z.fieldMap["is_deleted"] = z.IsDeleted
	z.fieldMap["created_by"] = z.CreatedBy
	z.fieldMap["updated_by"] = z.UpdatedBy
	z.fieldMap["created_at"] = z.CreatedAt
	z.fieldMap["published_at"] = z.PublishedAt
	z.fieldMap["updated_at"] = z.UpdatedAt
}

func (z ranFeedContent) clone(db *gorm.DB) ranFeedContent {
	z.ranFeedContentDo.ReplaceConnPool(db.Statement.ConnPool)
	return z
}

func (z ranFeedContent) replaceDB(db *gorm.DB) ranFeedContent {
	z.ranFeedContentDo.ReplaceDB(db)
	return z
}

type ranFeedContentDo struct{ gen.DO }

type IRanFeedContentDo interface {
	gen.SubQuery
	Debug() IRanFeedContentDo
	WithContext(ctx context.Context) IRanFeedContentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRanFeedContentDo
	WriteDB() IRanFeedContentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRanFeedContentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRanFeedContentDo
	Not(conds ...gen.Condition) IRanFeedContentDo
	Or(conds ...gen.Condition) IRanFeedContentDo
	Select(conds ...field.Expr) IRanFeedContentDo
	Where(conds ...gen.Condition) IRanFeedContentDo
	Order(conds ...field.Expr) IRanFeedContentDo
	Distinct(cols ...field.Expr) IRanFeedContentDo
	Omit(cols ...field.Expr) IRanFeedContentDo
	Join(table schema.Tabler, on ...field.Expr) IRanFeedContentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedContentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedContentDo
	Group(cols ...field.Expr) IRanFeedContentDo
	Having(conds ...gen.Condition) IRanFeedContentDo
	Limit(limit int) IRanFeedContentDo
	Offset(offset int) IRanFeedContentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedContentDo
	Unscoped() IRanFeedContentDo
	Create(values ...*model.RanFeedContent) error
	CreateInBatches(values []*model.RanFeedContent, batchSize int) error
	Save(values ...*model.RanFeedContent) error
	First() (*model.RanFeedContent, error)
	Take() (*model.RanFeedContent, error)
	Last() (*model.RanFeedContent, error)
	Find() ([]*model.RanFeedContent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedContent, err error)
	FindInBatches(result *[]*model.RanFeedContent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RanFeedContent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRanFeedContentDo
	Assign(attrs ...field.AssignExpr) IRanFeedContentDo
	Joins(fields ...field.RelationField) IRanFeedContentDo
	Preload(fields ...field.RelationField) IRanFeedContentDo
	FirstOrInit() (*model.RanFeedContent, error)
	FirstOrCreate() (*model.RanFeedContent, error)
	FindByPage(offset int, limit int) (result []*model.RanFeedContent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRanFeedContentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (z ranFeedContentDo) Debug() IRanFeedContentDo {
	return z.withDO(z.DO.Debug())
}

func (z ranFeedContentDo) WithContext(ctx context.Context) IRanFeedContentDo {
	return z.withDO(z.DO.WithContext(ctx))
}

func (z ranFeedContentDo) ReadDB() IRanFeedContentDo {
	return z.Clauses(dbresolver.Read)
}

func (z ranFeedContentDo) WriteDB() IRanFeedContentDo {
	return z.Clauses(dbresolver.Write)
}

func (z ranFeedContentDo) Session(config *gorm.Session) IRanFeedContentDo {
	return z.withDO(z.DO.Session(config))
}

func (z ranFeedContentDo) Clauses(conds ...clause.Expression) IRanFeedContentDo {
	return z.withDO(z.DO.Clauses(conds...))
}

func (z ranFeedContentDo) Returning(value interface{}, columns ...string) IRanFeedContentDo {
	return z.withDO(z.DO.Returning(value, columns...))
}

func (z ranFeedContentDo) Not(conds ...gen.Condition) IRanFeedContentDo {
	return z.withDO(z.DO.Not(conds...))
}

func (z ranFeedContentDo) Or(conds ...gen.Condition) IRanFeedContentDo {
	return z.withDO(z.DO.Or(conds...))
}

func (z ranFeedContentDo) Select(conds ...field.Expr) IRanFeedContentDo {
	return z.withDO(z.DO.Select(conds...))
}

func (z ranFeedContentDo) Where(conds ...gen.Condition) IRanFeedContentDo {
	return z.withDO(z.DO.Where(conds...))
}

func (z ranFeedContentDo) Order(conds ...field.Expr) IRanFeedContentDo {
	return z.withDO(z.DO.Order(conds...))
}

func (z ranFeedContentDo) Distinct(cols ...field.Expr) IRanFeedContentDo {
	return z.withDO(z.DO.Distinct(cols...))
}

func (z ranFeedContentDo) Omit(cols ...field.Expr) IRanFeedContentDo {
	return z.withDO(z.DO.Omit(cols...))
}

func (z ranFeedContentDo) Join(table schema.Tabler, on ...field.Expr) IRanFeedContentDo {
	return z.withDO(z.DO.Join(table, on...))
}

func (z ranFeedContentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedContentDo {
	return z.withDO(z.DO.LeftJoin(table, on...))
}

func (z ranFeedContentDo) RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedContentDo {
	return z.withDO(z.DO.RightJoin(table, on...))
}

func (z ranFeedContentDo) Group(cols ...field.Expr) IRanFeedContentDo {
	return z.withDO(z.DO.Group(cols...))
}

func (z ranFeedContentDo) Having(conds ...gen.Condition) IRanFeedContentDo {
	return z.withDO(z.DO.Having(conds...))
}

func (z ranFeedContentDo) Limit(limit int) IRanFeedContentDo {
	return z.withDO(z.DO.Limit(limit))
}

func (z ranFeedContentDo) Offset(offset int) IRanFeedContentDo {
	return z.withDO(z.DO.Offset(offset))
}

func (z ranFeedContentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedContentDo {
	return z.withDO(z.DO.Scopes(funcs...))
}

func (z ranFeedContentDo) Unscoped() IRanFeedContentDo {
	return z.withDO(z.DO.Unscoped())
}

func (z ranFeedContentDo) Create(values ...*model.RanFeedContent) error {
	if len(values) == 0 {
		return nil
	}
	return z.DO.Create(values)
}

func (z ranFeedContentDo) CreateInBatches(values []*model.RanFeedContent, batchSize int) error {
	return z.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (z ranFeedContentDo) Save(values ...*model.RanFeedContent) error {
	if len(values) == 0 {
		return nil
	}
	return z.DO.Save(values)
}

func (z ranFeedContentDo) First() (*model.RanFeedContent, error) {
	if result, err := z.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedContent), nil
	}
}

func (z ranFeedContentDo) Take() (*model.RanFeedContent, error) {
	if result, err := z.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedContent), nil
	}
}

func (z ranFeedContentDo) Last() (*model.RanFeedContent, error) {
	if result, err := z.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedContent), nil
	}
}

func (z ranFeedContentDo) Find() ([]*model.RanFeedContent, error) {
	result, err := z.DO.Find()
	return result.([]*model.RanFeedContent), err
}

func (z ranFeedContentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedContent, err error) {
	buf := make([]*model.RanFeedContent, 0, batchSize)
	err = z.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (z ranFeedContentDo) FindInBatches(result *[]*model.RanFeedContent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return z.DO.FindInBatches(result, batchSize, fc)
}

func (z ranFeedContentDo) Attrs(attrs ...field.AssignExpr) IRanFeedContentDo {
	return z.withDO(z.DO.Attrs(attrs...))
}

func (z ranFeedContentDo) Assign(attrs ...field.AssignExpr) IRanFeedContentDo {
	return z.withDO(z.DO.Assign(attrs...))
}

func (z ranFeedContentDo) Joins(fields ...field.RelationField) IRanFeedContentDo {
	for _, _f := range fields {
		z = *z.withDO(z.DO.Joins(_f))
	}
	return &z
}

func (z ranFeedContentDo) Preload(fields ...field.RelationField) IRanFeedContentDo {
	for _, _f := range fields {
		z = *z.withDO(z.DO.Preload(_f))
	}
	return &z
}

func (z ranFeedContentDo) FirstOrInit() (*model.RanFeedContent, error) {
	if result, err := z.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedContent), nil
	}
}

func (z ranFeedContentDo) FirstOrCreate() (*model.RanFeedContent, error) {
	if result, err := z.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedContent), nil
	}
}

func (z ranFeedContentDo) FindByPage(offset int, limit int) (result []*model.RanFeedContent, count int64, err error) {
	result, err = z.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = z.Offset(-1).Limit(-1).Count()
	return
}

func (z ranFeedContentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = z.Count()
	if err != nil {
		return
	}

	err = z.Offset(offset).Limit(limit).Scan(result)
	return
}

func (z ranFeedContentDo) Scan(result interface{}) (err error) {
	return z.DO.Scan(result)
}

func (z ranFeedContentDo) Delete(models ...*model.RanFeedContent) (result gen.ResultInfo, err error) {
	return z.DO.Delete(models)
}

func (z *ranFeedContentDo) withDO(do gen.Dao) *ranFeedContentDo {
	z.DO = *do.(*gen.DO)
	return z
}
