// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ran-feed/app/rpc/content/internal/entity/model"
)

func newRanFeedContentReview(db *gorm.DB, opts ...gen.DOOption) ranFeedContentReview {
	_ranFeedContentReview := ranFeedContentReview{}

	_ranFeedContentReview.ranFeedContentReviewDo.UseDB(db, opts...)
	_ranFeedContentReview.ranFeedContentReviewDo.UseModel(&model.RanFeedContentReview{})

	tableName := _ranFeedContentReview.ranFeedContentReviewDo.TableName()
	_ranFeedContentReview.ALL = field.NewAsterisk(tableName)
	_ranFeedContentReview.ID = field.NewInt64(tableName, "id")
	_ranFeedContentReview.ContentID = field.NewInt64(tableName, "content_id")
	_ranFeedContentReview.Decision = field.NewInt32(tableName, "decision")
	_ranFeedContentReview.Reason = field.NewString(tableName, "reason")
	_ranFeedContentReview.Version = field.NewInt32(tableName, "version")
	_ranFeedContentReview.IsDeleted = field.NewInt32(tableName, "is_deleted")
	_ranFeedContentReview.CreatedBy = field.NewInt64(tableName, "created_by")
	_ranFeedContentReview.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_ranFeedContentReview.CreatedAt = field.NewTime(tableName, "created_at")
	_ranFeedContentReview.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ranFeedContentReview.fillFieldMap()

	return _ranFeedContentReview
}

// ranFeedContentReview 内容审核记录表
type ranFeedContentReview struct {
	ranFeedContentReviewDo ranFeedContentReviewDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键id
	ContentID field.Int64  // 被审内容ID
	Decision  field.Int32  // 审核决策 10=通过 20=拒绝
	Reason    field.String // 拒绝理由 通过时为空
	Version   field.Int32  // 版本号（乐观锁）
	IsDeleted field.Int32  // 逻辑删除 0=正常 1=删除
	CreatedBy field.Int64  // 创建人（审核管理员 admin_user.id）
	UpdatedBy field.Int64  // 最后修改人
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (r ranFeedContentReview) Table(newTableName string) *ranFeedContentReview {
	r.ranFeedContentReviewDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r ranFeedContentReview) As(alias string) *ranFeedContentReview {
	r.ranFeedContentReviewDo.DO = *(r.ranFeedContentReviewDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *ranFeedContentReview) updateTableName(table string) *ranFeedContentReview {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.ContentID = field.NewInt64(table, "content_id")
	r.Decision = field.NewInt32(table, "decision")
	r.Reason = field.NewString(table, "reason")
	r.Version = field.NewInt32(table, "version")
	r.IsDeleted = field.NewInt32(table, "is_deleted")
	r.CreatedBy = field.NewInt64(table, "created_by")
	r.UpdatedBy = field.NewInt64(table, "updated_by")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *ranFeedContentReview) WithContext(ctx context.Context) IRanFeedContentReviewDo {
	return r.ranFeedContentReviewDo.WithContext(ctx)
}

func (r ranFeedContentReview) TableName() string { return r.ranFeedContentReviewDo.TableName() }

func (r ranFeedContentReview) Alias() string { return r.ranFeedContentReviewDo.Alias() }

func (r ranFeedContentReview) Columns(cols ...field.Expr) gen.Columns {
	return r.ranFeedContentReviewDo.Columns(cols...)
}

func (r *ranFeedContentReview) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *ranFeedContentReview) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 10)
	r.fieldMap["id"] = r.ID
	r.fieldMap["content_id"] = r.ContentID
	r.fieldMap["decision"] = r.Decision
	r.fieldMap["reason"] = r.Reason
	r.fieldMap["version"] = r.Version
	r.fieldMap["is_deleted"] = r.IsDeleted
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["updated_by"] = r.UpdatedBy
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r ranFeedContentReview) clone(db *gorm.DB) ranFeedContentReview {
	r.ranFeedContentReviewDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r ranFeedContentReview) replaceDB(db *gorm.DB) ranFeedContentReview {
	r.ranFeedContentReviewDo.ReplaceDB(db)
	return r
}

type ranFeedContentReviewDo struct{ gen.DO }

type IRanFeedContentReviewDo interface {
	gen.SubQuery
	Debug() IRanFeedContentReviewDo
	WithContext(ctx context.Context) IRanFeedContentReviewDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRanFeedContentReviewDo
	WriteDB() IRanFeedContentReviewDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRanFeedContentReviewDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRanFeedContentReviewDo
	Not(conds ...gen.Condition) IRanFeedContentReviewDo
	Or(conds ...gen.Condition) IRanFeedContentReviewDo
	Select(conds ...field.Expr) IRanFeedContentReviewDo
	Where(conds ...gen.Condition) IRanFeedContentReviewDo
	Order(conds ...field.Expr) IRanFeedContentReviewDo
	Distinct(cols ...field.Expr) IRanFeedContentReviewDo
	Omit(cols ...field.Expr) IRanFeedContentReviewDo
	Join(table schema.Tabler, on ...field.Expr) IRanFeedContentReviewDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedContentReviewDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedContentReviewDo
	Group(cols ...field.Expr) IRanFeedContentReviewDo
	Having(conds ...gen.Condition) IRanFeedContentReviewDo
	Limit(limit int) IRanFeedContentReviewDo
	Offset(offset int) IRanFeedContentReviewDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedContentReviewDo
	Unscoped() IRanFeedContentReviewDo
	Create(values ...*model.RanFeedContentReview) error
	CreateInBatches(values []*model.RanFeedContentReview, batchSize int) error
	Save(values ...*model.RanFeedContentReview) error
	First() (*model.RanFeedContentReview, error)
	Take() (*model.RanFeedContentReview, error)
	Last() (*model.RanFeedContentReview, error)
	Find() ([]*model.RanFeedContentReview, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedContentReview, err error)
	FindInBatches(result *[]*model.RanFeedContentReview, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RanFeedContentReview) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRanFeedContentReviewDo
	Assign(attrs ...field.AssignExpr) IRanFeedContentReviewDo
	Joins(fields ...field.RelationField) IRanFeedContentReviewDo
	Preload(fields ...field.RelationField) IRanFeedContentReviewDo
	FirstOrInit() (*model.RanFeedContentReview, error)
	FirstOrCreate() (*model.RanFeedContentReview, error)
	FindByPage(offset int, limit int) (result []*model.RanFeedContentReview, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRanFeedContentReviewDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r ranFeedContentReviewDo) Debug() IRanFeedContentReviewDo {
	return r.withDO(r.DO.Debug())
}

func (r ranFeedContentReviewDo) WithContext(ctx context.Context) IRanFeedContentReviewDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r ranFeedContentReviewDo) ReadDB() IRanFeedContentReviewDo {
	return r.Clauses(dbresolver.Read)
}

func (r ranFeedContentReviewDo) WriteDB() IRanFeedContentReviewDo {
	return r.Clauses(dbresolver.Write)
}

func (r ranFeedContentReviewDo) Session(config *gorm.Session) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Session(config))
}

func (r ranFeedContentReviewDo) Clauses(conds ...clause.Expression) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r ranFeedContentReviewDo) Returning(value interface{}, columns ...string) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r ranFeedContentReviewDo) Not(conds ...gen.Condition) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r ranFeedContentReviewDo) Or(conds ...gen.Condition) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r ranFeedContentReviewDo) Select(conds ...field.Expr) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r ranFeedContentReviewDo) Where(conds ...gen.Condition) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r ranFeedContentReviewDo) Order(conds ...field.Expr) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r ranFeedContentReviewDo) Distinct(cols ...field.Expr) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r ranFeedContentReviewDo) Omit(cols ...field.Expr) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r ranFeedContentReviewDo) Join(table schema.Tabler, on ...field.Expr) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r ranFeedContentReviewDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedContentReviewDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r ranFeedContentReviewDo) RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedContentReviewDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r ranFeedContentReviewDo) Group(cols ...field.Expr) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r ranFeedContentReviewDo) Having(conds ...gen.Condition) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r ranFeedContentReviewDo) Limit(limit int) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r ranFeedContentReviewDo) Offset(offset int) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r ranFeedContentReviewDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r ranFeedContentReviewDo) Unscoped() IRanFeedContentReviewDo {
	return r.withDO(r.DO.Unscoped())
}

func (r ranFeedContentReviewDo) Create(values ...*model.RanFeedContentReview) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r ranFeedContentReviewDo) CreateInBatches(values []*model.RanFeedContentReview, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r ranFeedContentReviewDo) Save(values ...*model.RanFeedContentReview) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r ranFeedContentReviewDo) First() (*model.RanFeedContentReview, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedContentReview), nil
	}
}

func (r ranFeedContentReviewDo) Take() (*model.RanFeedContentReview, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedContentReview), nil
	}
}

func (r ranFeedContentReviewDo) Last() (*model.RanFeedContentReview, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedContentReview), nil
	}
}

func (r ranFeedContentReviewDo) Find() ([]*model.RanFeedContentReview, error) {
	result, err := r.DO.Find()
	return result.([]*model.RanFeedContentReview), err
}

func (r ranFeedContentReviewDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedContentReview, err error) {
	buf := make([]*model.RanFeedContentReview, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r ranFeedContentReviewDo) FindInBatches(result *[]*model.RanFeedContentReview, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r ranFeedContentReviewDo) Attrs(attrs ...field.AssignExpr) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r ranFeedContentReviewDo) Assign(attrs ...field.AssignExpr) IRanFeedContentReviewDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r ranFeedContentReviewDo) Joins(fields ...field.RelationField) IRanFeedContentReviewDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r ranFeedContentReviewDo) Preload(fields ...field.RelationField) IRanFeedContentReviewDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r ranFeedContentReviewDo) FirstOrInit() (*model.RanFeedContentReview, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedContentReview), nil
	}
}

func (r ranFeedContentReviewDo) FirstOrCreate() (*model.RanFeedContentReview, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedContentReview), nil
	}
}

func (r ranFeedContentReviewDo) FindByPage(offset int, limit int) (result []*model.RanFeedContentReview, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r ranFeedContentReviewDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r ranFeedContentReviewDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r ranFeedContentReviewDo) Delete(models ...*model.RanFeedContentReview) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *ranFeedContentReviewDo) withDO(do gen.Dao) *ranFeedContentReviewDo {
	r.DO = *do.(*gen.DO)
	return r
}
