// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRanFeedVideo = "ran_feed_video"

// RanFeedVideo 视频内容表
type RanFeedVideo struct {
	ID              int64     `gorm:"column:id;primaryKey;comment:主键id" json:"id"`                                                     // 主键id
	ContentID       int64     `gorm:"column:content_id;not null;comment:contentID" json:"content_id"`                                  // contentID
	Title           string    `gorm:"column:title;not null;comment:标题" json:"title"`                                                   // 标题
	MediaID         int64     `gorm:"column:media_id;not null;comment:媒体资源ID（原始视频）" json:"media_id"`                                   // 媒体资源ID（原始视频）
	OriginURL       string    `gorm:"column:origin_url;not null;comment:原始视频地址" json:"origin_url"`                                     // 原始视频地址
	HlsURL          string    `gorm:"column:hls_url;not null;comment:HLS 播放地址" json:"hls_url"`                                         // HLS 播放地址
	CoverURL        string    `gorm:"column:cover_url;not null;comment:封面图地址" json:"cover_url"`                                        // 封面图地址
	Duration        int32     `gorm:"column:duration;not null;comment:视频时长（秒）" json:"duration"`                                        // 视频时长（秒）
	TranscodeStatus int32     `gorm:"column:transcode_status;not null;comment:转码状态 10=未开始 20=处理中 30=成功 40=失败" json:"transcode_status"` // 转码状态 10=未开始 20=处理中 30=成功 40=失败
	FailReason      string    `gorm:"column:fail_reason;not null;comment:失败原因" json:"fail_reason"`                                     // 失败原因
	Version         int32     `gorm:"column:version;not null;default:1;comment:版本号（乐观锁）" json:"version"`                               // 版本号（乐观锁）
	IsDeleted       int32     `gorm:"column:is_deleted;not null;comment:逻辑删除 0=正常 1=删除" json:"is_deleted"`                             // 逻辑删除 0=正常 1=删除
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`             // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`             // 更新时间
}

// TableName RanFeedVideo's table name
func (*RanFeedVideo) TableName() string {
	return TableNameRanFeedVideo
}
