// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: app/rpc/user/proto/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	commonpb "ran-feed/pkg/commonpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 性别
type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0 // 未知
	Gender_GENDER_MALE        Gender = 1 // 男
	Gender_GENDER_FEMALE      Gender = 2 // 女
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_app_rpc_user_proto_user_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_app_rpc_user_proto_user_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{0}
}

// 用户状态
type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0  // 未知
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 10 // 正常
	UserStatus_USER_STATUS_DISABLED    UserStatus = 20 // 禁用
	UserStatus_USER_STATUS_CANCELLED   UserStatus = 30 // 注销
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0:  "USER_STATUS_UNSPECIFIED",
		10: "USER_STATUS_ACTIVE",
		20: "USER_STATUS_DISABLED",
		30: "USER_STATUS_CANCELLED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      10,
		"USER_STATUS_DISABLED":    20,
		"USER_STATUS_CANCELLED":   30,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_app_rpc_user_proto_user_proto_enumTypes[1].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_app_rpc_user_proto_user_proto_enumTypes[1]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{1}
}

// 用户基础信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	Gender        *commonpb.EnumValue    `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Status        *commonpb.EnumValue    `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserInfo) GetGender() *commonpb.EnumValue {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *UserInfo) GetStatus() *commonpb.EnumValue {
	if x != nil {
		return x.Status
	}
	return nil
}

// 用户主页资料
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Gender        *commonpb.EnumValue    `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Status        *commonpb.EnumValue    `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetGender() *commonpb.EnumValue {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *UserProfile) GetStatus() *commonpb.EnumValue {
	if x != nil {
		return x.Status
	}
	return nil
}

// 注册请求
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           *string                `protobuf:"bytes,5,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Gender        Gender                 `protobuf:"varint,7,opt,name=gender,proto3,enum=ranfeed.user.Gender" json:"gender,omitempty"`
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RegisterReq) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *RegisterReq) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

// 注册响应
type RegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // 过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRes) Reset() {
	*x = RegisterRes{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRes) ProtoMessage() {}

func (x *RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRes.ProtoReflect.Descriptor instead.
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRes) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

// 登录请求
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应
type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // 过期时间
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRes) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *LoginRes) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LoginRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 退出登录请求
type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LogoutReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取当前用户信息请求
type GetMeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeReq) Reset() {
	*x = GetMeReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeReq) ProtoMessage() {}

func (x *GetMeReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeReq.ProtoReflect.Descriptor instead.
func (*GetMeReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetMeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取当前用户信息响应
type GetMeRes struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserInfo              *UserInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	FolloweeCount         int64                  `protobuf:"varint,2,opt,name=followee_count,json=followeeCount,proto3" json:"followee_count,omitempty"`
	FollowerCount         int64                  `protobuf:"varint,3,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	LikeReceivedCount     int64                  `protobuf:"varint,4,opt,name=like_received_count,json=likeReceivedCount,proto3" json:"like_received_count,omitempty"`
	FavoriteReceivedCount int64                  `protobuf:"varint,5,opt,name=favorite_received_count,json=favoriteReceivedCount,proto3" json:"favorite_received_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetMeRes) Reset() {
	*x = GetMeRes{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRes) ProtoMessage() {}

func (x *GetMeRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRes.ProtoReflect.Descriptor instead.
func (*GetMeRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetMeRes) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *GetMeRes) GetFolloweeCount() int64 {
	if x != nil {
		return x.FolloweeCount
	}
	return 0
}

func (x *GetMeRes) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *GetMeRes) GetLikeReceivedCount() int64 {
	if x != nil {
		return x.LikeReceivedCount
	}
	return 0
}

func (x *GetMeRes) GetFavoriteReceivedCount() int64 {
	if x != nil {
		return x.FavoriteReceivedCount
	}
	return 0
}

// 按 user_id 查询单个用户请求
type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 按 user_id 查询单个用户响应
type GetUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRes) Reset() {
	*x = GetUserRes{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRes) ProtoMessage() {}

func (x *GetUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRes.ProtoReflect.Descriptor instead.
func (*GetUserRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserRes) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// 查询用户主页资料请求
type GetUserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileReq) Reset() {
	*x = GetUserProfileReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileReq) ProtoMessage() {}

func (x *GetUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileReq.ProtoReflect.Descriptor instead.
func (*GetUserProfileReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 查询用户主页资料响应
type GetUserProfileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProfile   *UserProfile           `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRes) Reset() {
	*x = GetUserProfileRes{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRes) ProtoMessage() {}

func (x *GetUserProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRes.ProtoReflect.Descriptor instead.
func (*GetUserProfileRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserProfileRes) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// 批量查询用户信息请求
type BatchGetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserReq) Reset() {
	*x = BatchGetUserReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserReq) ProtoMessage() {}

func (x *BatchGetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserReq.ProtoReflect.Descriptor instead.
func (*BatchGetUserReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetUserReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 批量查询用户信息响应
type BatchGetUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserRes) Reset() {
	*x = BatchGetUserRes{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserRes) ProtoMessage() {}

func (x *BatchGetUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserRes.ProtoReflect.Descriptor instead.
func (*BatchGetUserRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *BatchGetUserRes) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// UserIndexItem 搜索建索引用的原始字段投影 只在可索引(正常+未删除)时返回
type UserIndexItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Status        UserStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=ranfeed.user.UserStatus" json:"status,omitempty"` // 恒为正常 带上供 search 纯拷贝写入
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`                            // user.updated_at 毫秒 供全量重建 ES external version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIndexItem) Reset() {
	*x = UserIndexItem{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIndexItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIndexItem) ProtoMessage() {}

func (x *UserIndexItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIndexItem.ProtoReflect.Descriptor instead.
func (*UserIndexItem) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserIndexItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserIndexItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserIndexItem) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserIndexItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserIndexItem) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *UserIndexItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// BatchGetUserForIndexReq 增量回源 按 user_id 批量取索引投影
type BatchGetUserForIndexReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserForIndexReq) Reset() {
	*x = BatchGetUserForIndexReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserForIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserForIndexReq) ProtoMessage() {}

func (x *BatchGetUserForIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserForIndexReq.ProtoReflect.Descriptor instead.
func (*BatchGetUserForIndexReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *BatchGetUserForIndexReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// BatchGetUserForIndexRes 增量回源响应
type BatchGetUserForIndexRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserIndexItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserForIndexRes) Reset() {
	*x = BatchGetUserForIndexRes{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserForIndexRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserForIndexRes) ProtoMessage() {}

func (x *BatchGetUserForIndexRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserForIndexRes.ProtoReflect.Descriptor instead.
func (*BatchGetUserForIndexRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *BatchGetUserForIndexRes) GetItems() []*UserIndexItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// ListUserForIndexReq 全量重建 按 id keyset 游标扫可索引用户
type ListUserForIndexReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserForIndexReq) Reset() {
	*x = ListUserForIndexReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserForIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserForIndexReq) ProtoMessage() {}

func (x *ListUserForIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserForIndexReq.ProtoReflect.Descriptor instead.
func (*ListUserForIndexReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *ListUserForIndexReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListUserForIndexReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListUserForIndexRes 全量重建响应
type ListUserForIndexRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserIndexItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserForIndexRes) Reset() {
	*x = ListUserForIndexRes{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserForIndexRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserForIndexRes) ProtoMessage() {}

func (x *ListUserForIndexRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserForIndexRes.ProtoReflect.Descriptor instead.
func (*ListUserForIndexRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{19}
}

func (x *ListUserForIndexRes) GetItems() []*UserIndexItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 后台管理用户条目
type AdminUserItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        *commonpb.EnumValue    `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserItem) Reset() {
	*x = AdminUserItem{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserItem) ProtoMessage() {}

func (x *AdminUserItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserItem.ProtoReflect.Descriptor instead.
func (*AdminUserItem) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{20}
}

func (x *AdminUserItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminUserItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUserItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminUserItem) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AdminUserItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdminUserItem) GetStatus() *commonpb.EnumValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AdminUserItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 后台管理用户详情
type AdminUserDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        *commonpb.EnumValue    `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Bio           string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	Gender        *commonpb.EnumValue    `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserDetail) Reset() {
	*x = AdminUserDetail{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserDetail) ProtoMessage() {}

func (x *AdminUserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserDetail.ProtoReflect.Descriptor instead.
func (*AdminUserDetail) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{21}
}

func (x *AdminUserDetail) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminUserDetail) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUserDetail) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminUserDetail) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AdminUserDetail) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdminUserDetail) GetStatus() *commonpb.EnumValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AdminUserDetail) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *AdminUserDetail) GetGender() *commonpb.EnumValue {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *AdminUserDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminUserDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdminUserDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 后台管理列表用户请求
type AdminListUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *UserStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=ranfeed.user.UserStatus,oneof" json:"status,omitempty"` // UNSPECIFIED=0 表示不限
	Keyword       *string                `protobuf:"bytes,2,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`                             // 昵称模糊搜索
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListUsersReq) Reset() {
	*x = AdminListUsersReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListUsersReq) ProtoMessage() {}

func (x *AdminListUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListUsersReq.ProtoReflect.Descriptor instead.
func (*AdminListUsersReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{22}
}

func (x *AdminListUsersReq) GetStatus() UserStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *AdminListUsersReq) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *AdminListUsersReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListUsersReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 后台管理列表用户响应
type AdminListUsersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AdminUserItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListUsersRes) Reset() {
	*x = AdminListUsersRes{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListUsersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListUsersRes) ProtoMessage() {}

func (x *AdminListUsersRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListUsersRes.ProtoReflect.Descriptor instead.
func (*AdminListUsersRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{23}
}

func (x *AdminListUsersRes) GetItems() []*AdminUserItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AdminListUsersRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminListUsersRes) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListUsersRes) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 后台管理获取用户详情请求
type AdminGetUserDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetUserDetailReq) Reset() {
	*x = AdminGetUserDetailReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetUserDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetUserDetailReq) ProtoMessage() {}

func (x *AdminGetUserDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetUserDetailReq.ProtoReflect.Descriptor instead.
func (*AdminGetUserDetailReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{24}
}

func (x *AdminGetUserDetailReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 后台管理获取用户详情响应
type AdminGetUserDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *AdminUserDetail       `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetUserDetailRes) Reset() {
	*x = AdminGetUserDetailRes{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetUserDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetUserDetailRes) ProtoMessage() {}

func (x *AdminGetUserDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetUserDetailRes.ProtoReflect.Descriptor instead.
func (*AdminGetUserDetailRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{25}
}

func (x *AdminGetUserDetailRes) GetDetail() *AdminUserDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

// 后台管理设置用户状态请求
type AdminSetUserStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        UserStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=ranfeed.user.UserStatus" json:"status,omitempty"`
	OperatorId    int64                  `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSetUserStatusReq) Reset() {
	*x = AdminSetUserStatusReq{}
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSetUserStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSetUserStatusReq) ProtoMessage() {}

func (x *AdminSetUserStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_user_proto_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSetUserStatusReq.ProtoReflect.Descriptor instead.
func (*AdminSetUserStatusReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_user_proto_user_proto_rawDescGZIP(), []int{26}
}

func (x *AdminSetUserStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminSetUserStatusReq) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *AdminSetUserStatusReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

var File_app_rpc_user_proto_user_proto protoreflect.FileDescriptor

const file_app_rpc_user_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x1dapp/rpc/user/proto/user.proto\x12\franfeed.user\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19pkg/commonpb/common.proto\"\x87\x02\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x123\n" +
	"\x06gender\x18\a \x01(\v2\x1b.ranfeed.commonpb.EnumValueR\x06gender\x123\n" +
	"\x06status\x18\b \x01(\v2\x1b.ranfeed.commonpb.EnumValueR\x06status\"\xd6\x01\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x123\n" +
	"\x06gender\x18\x05 \x01(\v2\x1b.ranfeed.commonpb.EnumValueR\x06gender\x123\n" +
	"\x06status\x18\x06 \x01(\v2\x1b.ranfeed.commonpb.EnumValueR\x06status\"\x90\x02\n" +
	"\vRegisterReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x15\n" +
	"\x03bio\x18\x05 \x01(\tH\x00R\x03bio\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12,\n" +
	"\x06gender\x18\a \x01(\x0e2\x14.ranfeed.user.GenderR\x06gender\x126\n" +
	"\bbirthday\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bbirthdayB\x06\n" +
	"\x04_bio\"w\n" +
	"\vRegisterRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\">\n" +
	"\bLoginReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa8\x01\n" +
	"\bLoginRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\":\n" +
	"\tLogoutReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"#\n" +
	"\bGetMeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xf5\x01\n" +
	"\bGetMeRes\x123\n" +
	"\tuser_info\x18\x01 \x01(\v2\x16.ranfeed.user.UserInfoR\buserInfo\x12%\n" +
	"\x0efollowee_count\x18\x02 \x01(\x03R\rfolloweeCount\x12%\n" +
	"\x0efollower_count\x18\x03 \x01(\x03R\rfollowerCount\x12.\n" +
	"\x13like_received_count\x18\x04 \x01(\x03R\x11likeReceivedCount\x126\n" +
	"\x17favorite_received_count\x18\x05 \x01(\x03R\x15favoriteReceivedCount\"%\n" +
	"\n" +
	"GetUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"A\n" +
	"\n" +
	"GetUserRes\x123\n" +
	"\tuser_info\x18\x01 \x01(\v2\x16.ranfeed.user.UserInfoR\buserInfo\",\n" +
	"\x11GetUserProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"Q\n" +
	"\x11GetUserProfileRes\x12<\n" +
	"\fuser_profile\x18\x01 \x01(\v2\x19.ranfeed.user.UserProfileR\vuserProfile\",\n" +
	"\x0fBatchGetUserReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"?\n" +
	"\x0fBatchGetUserRes\x12,\n" +
	"\x05users\x18\x01 \x03(\v2\x16.ranfeed.user.UserInfoR\x05users\"\xbe\x01\n" +
	"\rUserIndexItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.ranfeed.user.UserStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\"4\n" +
	"\x17BatchGetUserForIndexReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"L\n" +
	"\x17BatchGetUserForIndexRes\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.ranfeed.user.UserIndexItemR\x05items\"C\n" +
	"\x13ListUserForIndexReq\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"H\n" +
	"\x13ListUserForIndexRes\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.ranfeed.user.UserIndexItemR\x05items\"\x80\x02\n" +
	"\rAdminUserItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x123\n" +
	"\x06status\x18\x06 \x01(\v2\x1b.ranfeed.commonpb.EnumValueR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9a\x03\n" +
	"\x0fAdminUserDetail\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x123\n" +
	"\x06status\x18\x06 \x01(\v2\x1b.ranfeed.commonpb.EnumValueR\x06status\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x123\n" +
	"\x06gender\x18\b \x01(\v2\x1b.ranfeed.commonpb.EnumValueR\x06gender\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb1\x01\n" +
	"\x11AdminListUsersReq\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.ranfeed.user.UserStatusH\x00R\x06status\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x02 \x01(\tH\x01R\akeyword\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSizeB\t\n" +
	"\a_statusB\n" +
	"\n" +
	"\b_keyword\"\x8d\x01\n" +
	"\x11AdminListUsersRes\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.ranfeed.user.AdminUserItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"0\n" +
	"\x15AdminGetUserDetailReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"N\n" +
	"\x15AdminGetUserDetailRes\x125\n" +
	"\x06detail\x18\x01 \x01(\v2\x1d.ranfeed.user.AdminUserDetailR\x06detail\"\x83\x01\n" +
	"\x15AdminSetUserStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.ranfeed.user.UserStatusR\x06status\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x03R\n" +
	"operatorId*D\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02*v\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\n" +
	"\x12\x18\n" +
	"\x14USER_STATUS_DISABLED\x10\x14\x12\x19\n" +
	"\x15USER_STATUS_CANCELLED\x10\x1e2\x9d\x05\n" +
	"\vUserService\x12@\n" +
	"\bRegister\x12\x19.ranfeed.user.RegisterReq\x1a\x19.ranfeed.user.RegisterRes\x127\n" +
	"\x05Login\x12\x16.ranfeed.user.LoginReq\x1a\x16.ranfeed.user.LoginRes\x129\n" +
	"\x06Logout\x12\x17.ranfeed.user.LogoutReq\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x05GetMe\x12\x16.ranfeed.user.GetMeReq\x1a\x16.ranfeed.user.GetMeRes\x12=\n" +
	"\aGetUser\x12\x18.ranfeed.user.GetUserReq\x1a\x18.ranfeed.user.GetUserRes\x12R\n" +
	"\x0eGetUserProfile\x12\x1f.ranfeed.user.GetUserProfileReq\x1a\x1f.ranfeed.user.GetUserProfileRes\x12L\n" +
	"\fBatchGetUser\x12\x1d.ranfeed.user.BatchGetUserReq\x1a\x1d.ranfeed.user.BatchGetUserRes\x12d\n" +
	"\x14BatchGetUserForIndex\x12%.ranfeed.user.BatchGetUserForIndexReq\x1a%.ranfeed.user.BatchGetUserForIndexRes\x12X\n" +
	"\x10ListUserForIndex\x12!.ranfeed.user.ListUserForIndexReq\x1a!.ranfeed.user.ListUserForIndexRes2\x99\x02\n" +
	"\x10AdminUserService\x12R\n" +
	"\x0eAdminListUsers\x12\x1f.ranfeed.user.AdminListUsersReq\x1a\x1f.ranfeed.user.AdminListUsersRes\x12^\n" +
	"\x12AdminGetUserDetail\x12#.ranfeed.user.AdminGetUserDetailReq\x1a#.ranfeed.user.AdminGetUserDetailRes\x12Q\n" +
	"\x12AdminSetUserStatus\x12#.ranfeed.user.AdminSetUserStatusReq\x1a\x16.google.protobuf.EmptyB\x1cZ\x1aran-feed/app/rpc/user/userb\x06proto3"

var (
	file_app_rpc_user_proto_user_proto_rawDescOnce sync.Once
	file_app_rpc_user_proto_user_proto_rawDescData []byte
)

func file_app_rpc_user_proto_user_proto_rawDescGZIP() []byte {
	file_app_rpc_user_proto_user_proto_rawDescOnce.Do(func() {
		file_app_rpc_user_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_rpc_user_proto_user_proto_rawDesc), len(file_app_rpc_user_proto_user_proto_rawDesc)))
	})
	return file_app_rpc_user_proto_user_proto_rawDescData
}

var file_app_rpc_user_proto_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_app_rpc_user_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_app_rpc_user_proto_user_proto_goTypes = []any{
	(Gender)(0),                     // 0: ranfeed.user.Gender
	(UserStatus)(0),                 // 1: ranfeed.user.UserStatus
	(*UserInfo)(nil),                // 2: ranfeed.user.UserInfo
	(*UserProfile)(nil),             // 3: ranfeed.user.UserProfile
	(*RegisterReq)(nil),             // 4: ranfeed.user.RegisterReq
	(*RegisterRes)(nil),             // 5: ranfeed.user.RegisterRes
	(*LoginReq)(nil),                // 6: ranfeed.user.LoginReq
	(*LoginRes)(nil),                // 7: ranfeed.user.LoginRes
	(*LogoutReq)(nil),               // 8: ranfeed.user.LogoutReq
	(*GetMeReq)(nil),                // 9: ranfeed.user.GetMeReq
	(*GetMeRes)(nil),                // 10: ranfeed.user.GetMeRes
	(*GetUserReq)(nil),              // 11: ranfeed.user.GetUserReq
	(*GetUserRes)(nil),              // 12: ranfeed.user.GetUserRes
	(*GetUserProfileReq)(nil),       // 13: ranfeed.user.GetUserProfileReq
	(*GetUserProfileRes)(nil),       // 14: ranfeed.user.GetUserProfileRes
	(*BatchGetUserReq)(nil),         // 15: ranfeed.user.BatchGetUserReq
	(*BatchGetUserRes)(nil),         // 16: ranfeed.user.BatchGetUserRes
	(*UserIndexItem)(nil),           // 17: ranfeed.user.UserIndexItem
	(*BatchGetUserForIndexReq)(nil), // 18: ranfeed.user.BatchGetUserForIndexReq
	(*BatchGetUserForIndexRes)(nil), // 19: ranfeed.user.BatchGetUserForIndexRes
	(*ListUserForIndexReq)(nil),     // 20: ranfeed.user.ListUserForIndexReq
	(*ListUserForIndexRes)(nil),     // 21: ranfeed.user.ListUserForIndexRes
	(*AdminUserItem)(nil),           // 22: ranfeed.user.AdminUserItem
	(*AdminUserDetail)(nil),         // 23: ranfeed.user.AdminUserDetail
	(*AdminListUsersReq)(nil),       // 24: ranfeed.user.AdminListUsersReq
	(*AdminListUsersRes)(nil),       // 25: ranfeed.user.AdminListUsersRes
	(*AdminGetUserDetailReq)(nil),   // 26: ranfeed.user.AdminGetUserDetailReq
	(*AdminGetUserDetailRes)(nil),   // 27: ranfeed.user.AdminGetUserDetailRes
	(*AdminSetUserStatusReq)(nil),   // 28: ranfeed.user.AdminSetUserStatusReq
	(*commonpb.EnumValue)(nil),      // 29: ranfeed.commonpb.EnumValue
	(*timestamppb.Timestamp)(nil),   // 30: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 31: google.protobuf.Empty
}
var file_app_rpc_user_proto_user_proto_depIdxs = []int32{
	29, // 0: ranfeed.user.UserInfo.gender:type_name -> ranfeed.commonpb.EnumValue
	29, // 1: ranfeed.user.UserInfo.status:type_name -> ranfeed.commonpb.EnumValue
	29, // 2: ranfeed.user.UserProfile.gender:type_name -> ranfeed.commonpb.EnumValue
	29, // 3: ranfeed.user.UserProfile.status:type_name -> ranfeed.commonpb.EnumValue
	0,  // 4: ranfeed.user.RegisterReq.gender:type_name -> ranfeed.user.Gender
	30, // 5: ranfeed.user.RegisterReq.birthday:type_name -> google.protobuf.Timestamp
	30, // 6: ranfeed.user.RegisterRes.expired_at:type_name -> google.protobuf.Timestamp
	30, // 7: ranfeed.user.LoginRes.expired_at:type_name -> google.protobuf.Timestamp
	2,  // 8: ranfeed.user.GetMeRes.user_info:type_name -> ranfeed.user.UserInfo
	2,  // 9: ranfeed.user.GetUserRes.user_info:type_name -> ranfeed.user.UserInfo
	3,  // 10: ranfeed.user.GetUserProfileRes.user_profile:type_name -> ranfeed.user.UserProfile
	2,  // 11: ranfeed.user.BatchGetUserRes.users:type_name -> ranfeed.user.UserInfo
	1,  // 12: ranfeed.user.UserIndexItem.status:type_name -> ranfeed.user.UserStatus
	17, // 13: ranfeed.user.BatchGetUserForIndexRes.items:type_name -> ranfeed.user.UserIndexItem
	17, // 14: ranfeed.user.ListUserForIndexRes.items:type_name -> ranfeed.user.UserIndexItem
	29, // 15: ranfeed.user.AdminUserItem.status:type_name -> ranfeed.commonpb.EnumValue
	30, // 16: ranfeed.user.AdminUserItem.created_at:type_name -> google.protobuf.Timestamp
	29, // 17: ranfeed.user.AdminUserDetail.status:type_name -> ranfeed.commonpb.EnumValue
	29, // 18: ranfeed.user.AdminUserDetail.gender:type_name -> ranfeed.commonpb.EnumValue
	30, // 19: ranfeed.user.AdminUserDetail.created_at:type_name -> google.protobuf.Timestamp
	30, // 20: ranfeed.user.AdminUserDetail.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 21: ranfeed.user.AdminListUsersReq.status:type_name -> ranfeed.user.UserStatus
	22, // 22: ranfeed.user.AdminListUsersRes.items:type_name -> ranfeed.user.AdminUserItem
	23, // 23: ranfeed.user.AdminGetUserDetailRes.detail:type_name -> ranfeed.user.AdminUserDetail
	1,  // 24: ranfeed.user.AdminSetUserStatusReq.status:type_name -> ranfeed.user.UserStatus
	4,  // 25: ranfeed.user.UserService.Register:input_type -> ranfeed.user.RegisterReq
	6,  // 26: ranfeed.user.UserService.Login:input_type -> ranfeed.user.LoginReq
	8,  // 27: ranfeed.user.UserService.Logout:input_type -> ranfeed.user.LogoutReq
	9,  // 28: ranfeed.user.UserService.GetMe:input_type -> ranfeed.user.GetMeReq
	11, // 29: ranfeed.user.UserService.GetUser:input_type -> ranfeed.user.GetUserReq
	13, // 30: ranfeed.user.UserService.GetUserProfile:input_type -> ranfeed.user.GetUserProfileReq
	15, // 31: ranfeed.user.UserService.BatchGetUser:input_type -> ranfeed.user.BatchGetUserReq
	18, // 32: ranfeed.user.UserService.BatchGetUserForIndex:input_type -> ranfeed.user.BatchGetUserForIndexReq
	20, // 33: ranfeed.user.UserService.ListUserForIndex:input_type -> ranfeed.user.ListUserForIndexReq
	24, // 34: ranfeed.user.AdminUserService.AdminListUsers:input_type -> ranfeed.user.AdminListUsersReq
	26, // 35: ranfeed.user.AdminUserService.AdminGetUserDetail:input_type -> ranfeed.user.AdminGetUserDetailReq
	28, // 36: ranfeed.user.AdminUserService.AdminSetUserStatus:input_type -> ranfeed.user.AdminSetUserStatusReq
	5,  // 37: ranfeed.user.UserService.Register:output_type -> ranfeed.user.RegisterRes
	7,  // 38: ranfeed.user.UserService.Login:output_type -> ranfeed.user.LoginRes
	31, // 39: ranfeed.user.UserService.Logout:output_type -> google.protobuf.Empty
	10, // 40: ranfeed.user.UserService.GetMe:output_type -> ranfeed.user.GetMeRes
	12, // 41: ranfeed.user.UserService.GetUser:output_type -> ranfeed.user.GetUserRes
	14, // 42: ranfeed.user.UserService.GetUserProfile:output_type -> ranfeed.user.GetUserProfileRes
	16, // 43: ranfeed.user.UserService.BatchGetUser:output_type -> ranfeed.user.BatchGetUserRes
	19, // 44: ranfeed.user.UserService.BatchGetUserForIndex:output_type -> ranfeed.user.BatchGetUserForIndexRes
	21, // 45: ranfeed.user.UserService.ListUserForIndex:output_type -> ranfeed.user.ListUserForIndexRes
	25, // 46: ranfeed.user.AdminUserService.AdminListUsers:output_type -> ranfeed.user.AdminListUsersRes
	27, // 47: ranfeed.user.AdminUserService.AdminGetUserDetail:output_type -> ranfeed.user.AdminGetUserDetailRes
	31, // 48: ranfeed.user.AdminUserService.AdminSetUserStatus:output_type -> google.protobuf.Empty
	37, // [37:49] is the sub-list for method output_type
	25, // [25:37] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_app_rpc_user_proto_user_proto_init() }
func file_app_rpc_user_proto_user_proto_init() {
	if File_app_rpc_user_proto_user_proto != nil {
		return
	}
	file_app_rpc_user_proto_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_app_rpc_user_proto_user_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_rpc_user_proto_user_proto_rawDesc), len(file_app_rpc_user_proto_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_app_rpc_user_proto_user_proto_goTypes,
		DependencyIndexes: file_app_rpc_user_proto_user_proto_depIdxs,
		EnumInfos:         file_app_rpc_user_proto_user_proto_enumTypes,
		MessageInfos:      file_app_rpc_user_proto_user_proto_msgTypes,
	}.Build()
	File_app_rpc_user_proto_user_proto = out.File
	file_app_rpc_user_proto_user_proto_goTypes = nil
	file_app_rpc_user_proto_user_proto_depIdxs = nil
}
