// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: admin.proto

package adminauthservice

import (
	"context"

	"ran-feed/app/rpc/admin/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetAdminReq             = admin.GetAdminReq
	GetAdminRes             = admin.GetAdminRes
	ListAdminPermissionsReq = admin.ListAdminPermissionsReq
	ListAdminPermissionsRes = admin.ListAdminPermissionsRes
	LoginReq                = admin.LoginReq
	LoginRes                = admin.LoginRes

	AdminAuthService interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
		GetAdmin(ctx context.Context, in *GetAdminReq, opts ...grpc.CallOption) (*GetAdminRes, error)
		ListAdminPermissions(ctx context.Context, in *ListAdminPermissionsReq, opts ...grpc.CallOption) (*ListAdminPermissionsRes, error)
	}

	defaultAdminAuthService struct {
		cli zrpc.Client
	}
)

func NewAdminAuthService(cli zrpc.Client) AdminAuthService {
	return &defaultAdminAuthService{
		cli: cli,
	}
}

func (m *defaultAdminAuthService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	client := admin.NewAdminAuthServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAdminAuthService) GetAdmin(ctx context.Context, in *GetAdminReq, opts ...grpc.CallOption) (*GetAdminRes, error) {
	client := admin.NewAdminAuthServiceClient(m.cli.Conn())
	return client.GetAdmin(ctx, in, opts...)
}

func (m *defaultAdminAuthService) ListAdminPermissions(ctx context.Context, in *ListAdminPermissionsReq, opts ...grpc.CallOption) (*ListAdminPermissionsRes, error) {
	client := admin.NewAdminAuthServiceClient(m.cli.Conn())
	return client.ListAdminPermissions(ctx, in, opts...)
}
