// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ran-feed/app/rpc/interaction/internal/entity/model"
)

func newRanFeedComment(db *gorm.DB, opts ...gen.DOOption) ranFeedComment {
	_ranFeedComment := ranFeedComment{}

	_ranFeedComment.ranFeedCommentDo.UseDB(db, opts...)
	_ranFeedComment.ranFeedCommentDo.UseModel(&model.RanFeedComment{})

	tableName := _ranFeedComment.ranFeedCommentDo.TableName()
	_ranFeedComment.ALL = field.NewAsterisk(tableName)
	_ranFeedComment.ID = field.NewInt64(tableName, "id")
	_ranFeedComment.ContentID = field.NewInt64(tableName, "content_id")
	_ranFeedComment.ContentUserID = field.NewInt64(tableName, "content_user_id")
	_ranFeedComment.UserID = field.NewInt64(tableName, "user_id")
	_ranFeedComment.ReplyToUserID = field.NewInt64(tableName, "reply_to_user_id")
	_ranFeedComment.ParentID = field.NewInt64(tableName, "parent_id")
	_ranFeedComment.RootID = field.NewInt64(tableName, "root_id")
	_ranFeedComment.Comment = field.NewString(tableName, "comment")
	_ranFeedComment.Status = field.NewInt32(tableName, "status")
	_ranFeedComment.Version = field.NewInt32(tableName, "version")
	_ranFeedComment.IsDeleted = field.NewInt32(tableName, "is_deleted")
	_ranFeedComment.CreatedBy = field.NewInt64(tableName, "created_by")
	_ranFeedComment.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_ranFeedComment.CreatedAt = field.NewTime(tableName, "created_at")
	_ranFeedComment.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ranFeedComment.fillFieldMap()

	return _ranFeedComment
}

// ranFeedComment 内容评论表
type ranFeedComment struct {
	ranFeedCommentDo ranFeedCommentDo

	ALL           field.Asterisk
	ID            field.Int64  // 评论ID
	ContentID     field.Int64  // 内容ID
	ContentUserID field.Int64  // 内容作者ID
	UserID        field.Int64  // 评论用户
	ReplyToUserID field.Int64  // 被回复用户ID
	ParentID      field.Int64  // 父评论ID，0表示一级评论
	RootID        field.Int64  // 根评论ID
	Comment       field.String // 评论内容
	Status        field.Int32  // 状态 10=正常 20=删除
	Version       field.Int32  // 版本号（乐观锁）
	IsDeleted     field.Int32  // 逻辑删除 0=正常 1=删除
	CreatedBy     field.Int64  // 创建人
	UpdatedBy     field.Int64  // 最后修改人
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (r ranFeedComment) Table(newTableName string) *ranFeedComment {
	r.ranFeedCommentDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r ranFeedComment) As(alias string) *ranFeedComment {
	r.ranFeedCommentDo.DO = *(r.ranFeedCommentDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *ranFeedComment) updateTableName(table string) *ranFeedComment {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.ContentID = field.NewInt64(table, "content_id")
	r.ContentUserID = field.NewInt64(table, "content_user_id")
	r.UserID = field.NewInt64(table, "user_id")
	r.ReplyToUserID = field.NewInt64(table, "reply_to_user_id")
	r.ParentID = field.NewInt64(table, "parent_id")
	r.RootID = field.NewInt64(table, "root_id")
	r.Comment = field.NewString(table, "comment")
	r.Status = field.NewInt32(table, "status")
	r.Version = field.NewInt32(table, "version")
	r.IsDeleted = field.NewInt32(table, "is_deleted")
	r.CreatedBy = field.NewInt64(table, "created_by")
	r.UpdatedBy = field.NewInt64(table, "updated_by")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *ranFeedComment) WithContext(ctx context.Context) IRanFeedCommentDo {
	return r.ranFeedCommentDo.WithContext(ctx)
}

func (r ranFeedComment) TableName() string { return r.ranFeedCommentDo.TableName() }

func (r ranFeedComment) Alias() string { return r.ranFeedCommentDo.Alias() }

func (r ranFeedComment) Columns(cols ...field.Expr) gen.Columns {
	return r.ranFeedCommentDo.Columns(cols...)
}

func (r *ranFeedComment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *ranFeedComment) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 15)
	r.fieldMap["id"] = r.ID
	r.fieldMap["content_id"] = r.ContentID
	r.fieldMap["content_user_id"] = r.ContentUserID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["reply_to_user_id"] = r.ReplyToUserID
	r.fieldMap["parent_id"] = r.ParentID
	r.fieldMap["root_id"] = r.RootID
	r.fieldMap["comment"] = r.Comment
	r.fieldMap["status"] = r.Status
	r.fieldMap["version"] = r.Version
	r.fieldMap["is_deleted"] = r.IsDeleted
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["updated_by"] = r.UpdatedBy
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r ranFeedComment) clone(db *gorm.DB) ranFeedComment {
	r.ranFeedCommentDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r ranFeedComment) replaceDB(db *gorm.DB) ranFeedComment {
	r.ranFeedCommentDo.ReplaceDB(db)
	return r
}

type ranFeedCommentDo struct{ gen.DO }

type IRanFeedCommentDo interface {
	gen.SubQuery
	Debug() IRanFeedCommentDo
	WithContext(ctx context.Context) IRanFeedCommentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRanFeedCommentDo
	WriteDB() IRanFeedCommentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRanFeedCommentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRanFeedCommentDo
	Not(conds ...gen.Condition) IRanFeedCommentDo
	Or(conds ...gen.Condition) IRanFeedCommentDo
	Select(conds ...field.Expr) IRanFeedCommentDo
	Where(conds ...gen.Condition) IRanFeedCommentDo
	Order(conds ...field.Expr) IRanFeedCommentDo
	Distinct(cols ...field.Expr) IRanFeedCommentDo
	Omit(cols ...field.Expr) IRanFeedCommentDo
	Join(table schema.Tabler, on ...field.Expr) IRanFeedCommentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedCommentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedCommentDo
	Group(cols ...field.Expr) IRanFeedCommentDo
	Having(conds ...gen.Condition) IRanFeedCommentDo
	Limit(limit int) IRanFeedCommentDo
	Offset(offset int) IRanFeedCommentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedCommentDo
	Unscoped() IRanFeedCommentDo
	Create(values ...*model.RanFeedComment) error
	CreateInBatches(values []*model.RanFeedComment, batchSize int) error
	Save(values ...*model.RanFeedComment) error
	First() (*model.RanFeedComment, error)
	Take() (*model.RanFeedComment, error)
	Last() (*model.RanFeedComment, error)
	Find() ([]*model.RanFeedComment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedComment, err error)
	FindInBatches(result *[]*model.RanFeedComment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RanFeedComment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRanFeedCommentDo
	Assign(attrs ...field.AssignExpr) IRanFeedCommentDo
	Joins(fields ...field.RelationField) IRanFeedCommentDo
	Preload(fields ...field.RelationField) IRanFeedCommentDo
	FirstOrInit() (*model.RanFeedComment, error)
	FirstOrCreate() (*model.RanFeedComment, error)
	FindByPage(offset int, limit int) (result []*model.RanFeedComment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRanFeedCommentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r ranFeedCommentDo) Debug() IRanFeedCommentDo {
	return r.withDO(r.DO.Debug())
}

func (r ranFeedCommentDo) WithContext(ctx context.Context) IRanFeedCommentDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r ranFeedCommentDo) ReadDB() IRanFeedCommentDo {
	return r.Clauses(dbresolver.Read)
}

func (r ranFeedCommentDo) WriteDB() IRanFeedCommentDo {
	return r.Clauses(dbresolver.Write)
}

func (r ranFeedCommentDo) Session(config *gorm.Session) IRanFeedCommentDo {
	return r.withDO(r.DO.Session(config))
}

func (r ranFeedCommentDo) Clauses(conds ...clause.Expression) IRanFeedCommentDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r ranFeedCommentDo) Returning(value interface{}, columns ...string) IRanFeedCommentDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r ranFeedCommentDo) Not(conds ...gen.Condition) IRanFeedCommentDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r ranFeedCommentDo) Or(conds ...gen.Condition) IRanFeedCommentDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r ranFeedCommentDo) Select(conds ...field.Expr) IRanFeedCommentDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r ranFeedCommentDo) Where(conds ...gen.Condition) IRanFeedCommentDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r ranFeedCommentDo) Order(conds ...field.Expr) IRanFeedCommentDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r ranFeedCommentDo) Distinct(cols ...field.Expr) IRanFeedCommentDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r ranFeedCommentDo) Omit(cols ...field.Expr) IRanFeedCommentDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r ranFeedCommentDo) Join(table schema.Tabler, on ...field.Expr) IRanFeedCommentDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r ranFeedCommentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedCommentDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r ranFeedCommentDo) RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedCommentDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r ranFeedCommentDo) Group(cols ...field.Expr) IRanFeedCommentDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r ranFeedCommentDo) Having(conds ...gen.Condition) IRanFeedCommentDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r ranFeedCommentDo) Limit(limit int) IRanFeedCommentDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r ranFeedCommentDo) Offset(offset int) IRanFeedCommentDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r ranFeedCommentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedCommentDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r ranFeedCommentDo) Unscoped() IRanFeedCommentDo {
	return r.withDO(r.DO.Unscoped())
}

func (r ranFeedCommentDo) Create(values ...*model.RanFeedComment) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r ranFeedCommentDo) CreateInBatches(values []*model.RanFeedComment, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r ranFeedCommentDo) Save(values ...*model.RanFeedComment) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r ranFeedCommentDo) First() (*model.RanFeedComment, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedComment), nil
	}
}

func (r ranFeedCommentDo) Take() (*model.RanFeedComment, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedComment), nil
	}
}

func (r ranFeedCommentDo) Last() (*model.RanFeedComment, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedComment), nil
	}
}

func (r ranFeedCommentDo) Find() ([]*model.RanFeedComment, error) {
	result, err := r.DO.Find()
	return result.([]*model.RanFeedComment), err
}

func (r ranFeedCommentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedComment, err error) {
	buf := make([]*model.RanFeedComment, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r ranFeedCommentDo) FindInBatches(result *[]*model.RanFeedComment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r ranFeedCommentDo) Attrs(attrs ...field.AssignExpr) IRanFeedCommentDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r ranFeedCommentDo) Assign(attrs ...field.AssignExpr) IRanFeedCommentDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r ranFeedCommentDo) Joins(fields ...field.RelationField) IRanFeedCommentDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r ranFeedCommentDo) Preload(fields ...field.RelationField) IRanFeedCommentDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r ranFeedCommentDo) FirstOrInit() (*model.RanFeedComment, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedComment), nil
	}
}

func (r ranFeedCommentDo) FirstOrCreate() (*model.RanFeedComment, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedComment), nil
	}
}

func (r ranFeedCommentDo) FindByPage(offset int, limit int) (result []*model.RanFeedComment, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r ranFeedCommentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r ranFeedCommentDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r ranFeedCommentDo) Delete(models ...*model.RanFeedComment) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *ranFeedCommentDo) withDO(do gen.Dao) *ranFeedCommentDo {
	r.DO = *do.(*gen.DO)
	return r
}
