// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ran-feed/app/rpc/interaction/internal/entity/model"
)

func newRanFeedLike(db *gorm.DB, opts ...gen.DOOption) ranFeedLike {
	_ranFeedLike := ranFeedLike{}

	_ranFeedLike.ranFeedLikeDo.UseDB(db, opts...)
	_ranFeedLike.ranFeedLikeDo.UseModel(&model.RanFeedLike{})

	tableName := _ranFeedLike.ranFeedLikeDo.TableName()
	_ranFeedLike.ALL = field.NewAsterisk(tableName)
	_ranFeedLike.ID = field.NewInt64(tableName, "id")
	_ranFeedLike.UserID = field.NewInt64(tableName, "user_id")
	_ranFeedLike.ContentID = field.NewInt64(tableName, "content_id")
	_ranFeedLike.ContentUserID = field.NewInt64(tableName, "content_user_id")
	_ranFeedLike.Status = field.NewInt32(tableName, "status")
	_ranFeedLike.Version = field.NewInt32(tableName, "version")
	_ranFeedLike.IsDeleted = field.NewInt32(tableName, "is_deleted")
	_ranFeedLike.CreatedBy = field.NewInt64(tableName, "created_by")
	_ranFeedLike.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_ranFeedLike.CreatedAt = field.NewTime(tableName, "created_at")
	_ranFeedLike.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ranFeedLike.fillFieldMap()

	return _ranFeedLike
}

// ranFeedLike 内容点赞行为表
type ranFeedLike struct {
	ranFeedLikeDo ranFeedLikeDo

	ALL           field.Asterisk
	ID            field.Int64 // 主键ID
	UserID        field.Int64 // 用户ID
	ContentID     field.Int64 // 内容ID
	ContentUserID field.Int64 // 内容作者ID
	Status        field.Int32 // 状态 10=点赞 20=取消
	Version       field.Int32 // 版本号（乐观锁）
	IsDeleted     field.Int32 // 逻辑删除 0=正常 1=删除
	CreatedBy     field.Int64 // 创建人
	UpdatedBy     field.Int64 // 最后修改人
	CreatedAt     field.Time  // 创建时间
	UpdatedAt     field.Time  // 更新时间

	fieldMap map[string]field.Expr
}

func (z ranFeedLike) Table(newTableName string) *ranFeedLike {
	z.ranFeedLikeDo.UseTable(newTableName)
	return z.updateTableName(newTableName)
}

func (z ranFeedLike) As(alias string) *ranFeedLike {
	z.ranFeedLikeDo.DO = *(z.ranFeedLikeDo.As(alias).(*gen.DO))
	return z.updateTableName(alias)
}

func (z *ranFeedLike) updateTableName(table string) *ranFeedLike {
	z.ALL = field.NewAsterisk(table)
	z.ID = field.NewInt64(table, "id")
	z.UserID = field.NewInt64(table, "user_id")
	z.ContentID = field.NewInt64(table, "content_id")
	z.ContentUserID = field.NewInt64(table, "content_user_id")
	z.Status = field.NewInt32(table, "status")
	z.Version = field.NewInt32(table, "version")
	z.IsDeleted = field.NewInt32(table, "is_deleted")
	z.CreatedBy = field.NewInt64(table, "created_by")
	z.UpdatedBy = field.NewInt64(table, "updated_by")
	z.CreatedAt = field.NewTime(table, "created_at")
	z.UpdatedAt = field.NewTime(table, "updated_at")

	z.fillFieldMap()

	return z
}

func (z *ranFeedLike) WithContext(ctx context.Context) IRanFeedLikeDo {
	return z.ranFeedLikeDo.WithContext(ctx)
}

func (z ranFeedLike) TableName() string { return z.ranFeedLikeDo.TableName() }

func (z ranFeedLike) Alias() string { return z.ranFeedLikeDo.Alias() }

func (z ranFeedLike) Columns(cols ...field.Expr) gen.Columns {
	return z.ranFeedLikeDo.Columns(cols...)
}

func (z *ranFeedLike) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := z.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (z *ranFeedLike) fillFieldMap() {
	z.fieldMap = make(map[string]field.Expr, 11)
	z.fieldMap["id"] = z.ID
	z.fieldMap["user_id"] = z.UserID
	z.fieldMap["content_id"] = z.ContentID
	z.fieldMap["content_user_id"] = z.ContentUserID
	z.fieldMap["status"] = z.Status
	z.fieldMap["version"] = z.Version
	z.fieldMap["is_deleted"] = z.IsDeleted
	z.fieldMap["created_by"] = z.CreatedBy
	z.fieldMap["updated_by"] = z.UpdatedBy
	z.fieldMap["created_at"] = z.CreatedAt
	z.fieldMap["updated_at"] = z.UpdatedAt
}

func (z ranFeedLike) clone(db *gorm.DB) ranFeedLike {
	z.ranFeedLikeDo.ReplaceConnPool(db.Statement.ConnPool)
	return z
}

func (z ranFeedLike) replaceDB(db *gorm.DB) ranFeedLike {
	z.ranFeedLikeDo.ReplaceDB(db)
	return z
}

type ranFeedLikeDo struct{ gen.DO }

type IRanFeedLikeDo interface {
	gen.SubQuery
	Debug() IRanFeedLikeDo
	WithContext(ctx context.Context) IRanFeedLikeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRanFeedLikeDo
	WriteDB() IRanFeedLikeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRanFeedLikeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRanFeedLikeDo
	Not(conds ...gen.Condition) IRanFeedLikeDo
	Or(conds ...gen.Condition) IRanFeedLikeDo
	Select(conds ...field.Expr) IRanFeedLikeDo
	Where(conds ...gen.Condition) IRanFeedLikeDo
	Order(conds ...field.Expr) IRanFeedLikeDo
	Distinct(cols ...field.Expr) IRanFeedLikeDo
	Omit(cols ...field.Expr) IRanFeedLikeDo
	Join(table schema.Tabler, on ...field.Expr) IRanFeedLikeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedLikeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedLikeDo
	Group(cols ...field.Expr) IRanFeedLikeDo
	Having(conds ...gen.Condition) IRanFeedLikeDo
	Limit(limit int) IRanFeedLikeDo
	Offset(offset int) IRanFeedLikeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedLikeDo
	Unscoped() IRanFeedLikeDo
	Create(values ...*model.RanFeedLike) error
	CreateInBatches(values []*model.RanFeedLike, batchSize int) error
	Save(values ...*model.RanFeedLike) error
	First() (*model.RanFeedLike, error)
	Take() (*model.RanFeedLike, error)
	Last() (*model.RanFeedLike, error)
	Find() ([]*model.RanFeedLike, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedLike, err error)
	FindInBatches(result *[]*model.RanFeedLike, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RanFeedLike) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRanFeedLikeDo
	Assign(attrs ...field.AssignExpr) IRanFeedLikeDo
	Joins(fields ...field.RelationField) IRanFeedLikeDo
	Preload(fields ...field.RelationField) IRanFeedLikeDo
	FirstOrInit() (*model.RanFeedLike, error)
	FirstOrCreate() (*model.RanFeedLike, error)
	FindByPage(offset int, limit int) (result []*model.RanFeedLike, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRanFeedLikeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (z ranFeedLikeDo) Debug() IRanFeedLikeDo {
	return z.withDO(z.DO.Debug())
}

func (z ranFeedLikeDo) WithContext(ctx context.Context) IRanFeedLikeDo {
	return z.withDO(z.DO.WithContext(ctx))
}

func (z ranFeedLikeDo) ReadDB() IRanFeedLikeDo {
	return z.Clauses(dbresolver.Read)
}

func (z ranFeedLikeDo) WriteDB() IRanFeedLikeDo {
	return z.Clauses(dbresolver.Write)
}

func (z ranFeedLikeDo) Session(config *gorm.Session) IRanFeedLikeDo {
	return z.withDO(z.DO.Session(config))
}

func (z ranFeedLikeDo) Clauses(conds ...clause.Expression) IRanFeedLikeDo {
	return z.withDO(z.DO.Clauses(conds...))
}

func (z ranFeedLikeDo) Returning(value interface{}, columns ...string) IRanFeedLikeDo {
	return z.withDO(z.DO.Returning(value, columns...))
}

func (z ranFeedLikeDo) Not(conds ...gen.Condition) IRanFeedLikeDo {
	return z.withDO(z.DO.Not(conds...))
}

func (z ranFeedLikeDo) Or(conds ...gen.Condition) IRanFeedLikeDo {
	return z.withDO(z.DO.Or(conds...))
}

func (z ranFeedLikeDo) Select(conds ...field.Expr) IRanFeedLikeDo {
	return z.withDO(z.DO.Select(conds...))
}

func (z ranFeedLikeDo) Where(conds ...gen.Condition) IRanFeedLikeDo {
	return z.withDO(z.DO.Where(conds...))
}

func (z ranFeedLikeDo) Order(conds ...field.Expr) IRanFeedLikeDo {
	return z.withDO(z.DO.Order(conds...))
}

func (z ranFeedLikeDo) Distinct(cols ...field.Expr) IRanFeedLikeDo {
	return z.withDO(z.DO.Distinct(cols...))
}

func (z ranFeedLikeDo) Omit(cols ...field.Expr) IRanFeedLikeDo {
	return z.withDO(z.DO.Omit(cols...))
}

func (z ranFeedLikeDo) Join(table schema.Tabler, on ...field.Expr) IRanFeedLikeDo {
	return z.withDO(z.DO.Join(table, on...))
}

func (z ranFeedLikeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRanFeedLikeDo {
	return z.withDO(z.DO.LeftJoin(table, on...))
}

func (z ranFeedLikeDo) RightJoin(table schema.Tabler, on ...field.Expr) IRanFeedLikeDo {
	return z.withDO(z.DO.RightJoin(table, on...))
}

func (z ranFeedLikeDo) Group(cols ...field.Expr) IRanFeedLikeDo {
	return z.withDO(z.DO.Group(cols...))
}

func (z ranFeedLikeDo) Having(conds ...gen.Condition) IRanFeedLikeDo {
	return z.withDO(z.DO.Having(conds...))
}

func (z ranFeedLikeDo) Limit(limit int) IRanFeedLikeDo {
	return z.withDO(z.DO.Limit(limit))
}

func (z ranFeedLikeDo) Offset(offset int) IRanFeedLikeDo {
	return z.withDO(z.DO.Offset(offset))
}

func (z ranFeedLikeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRanFeedLikeDo {
	return z.withDO(z.DO.Scopes(funcs...))
}

func (z ranFeedLikeDo) Unscoped() IRanFeedLikeDo {
	return z.withDO(z.DO.Unscoped())
}

func (z ranFeedLikeDo) Create(values ...*model.RanFeedLike) error {
	if len(values) == 0 {
		return nil
	}
	return z.DO.Create(values)
}

func (z ranFeedLikeDo) CreateInBatches(values []*model.RanFeedLike, batchSize int) error {
	return z.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (z ranFeedLikeDo) Save(values ...*model.RanFeedLike) error {
	if len(values) == 0 {
		return nil
	}
	return z.DO.Save(values)
}

func (z ranFeedLikeDo) First() (*model.RanFeedLike, error) {
	if result, err := z.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedLike), nil
	}
}

func (z ranFeedLikeDo) Take() (*model.RanFeedLike, error) {
	if result, err := z.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedLike), nil
	}
}

func (z ranFeedLikeDo) Last() (*model.RanFeedLike, error) {
	if result, err := z.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedLike), nil
	}
}

func (z ranFeedLikeDo) Find() ([]*model.RanFeedLike, error) {
	result, err := z.DO.Find()
	return result.([]*model.RanFeedLike), err
}

func (z ranFeedLikeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RanFeedLike, err error) {
	buf := make([]*model.RanFeedLike, 0, batchSize)
	err = z.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (z ranFeedLikeDo) FindInBatches(result *[]*model.RanFeedLike, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return z.DO.FindInBatches(result, batchSize, fc)
}

func (z ranFeedLikeDo) Attrs(attrs ...field.AssignExpr) IRanFeedLikeDo {
	return z.withDO(z.DO.Attrs(attrs...))
}

func (z ranFeedLikeDo) Assign(attrs ...field.AssignExpr) IRanFeedLikeDo {
	return z.withDO(z.DO.Assign(attrs...))
}

func (z ranFeedLikeDo) Joins(fields ...field.RelationField) IRanFeedLikeDo {
	for _, _f := range fields {
		z = *z.withDO(z.DO.Joins(_f))
	}
	return &z
}

func (z ranFeedLikeDo) Preload(fields ...field.RelationField) IRanFeedLikeDo {
	for _, _f := range fields {
		z = *z.withDO(z.DO.Preload(_f))
	}
	return &z
}

func (z ranFeedLikeDo) FirstOrInit() (*model.RanFeedLike, error) {
	if result, err := z.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedLike), nil
	}
}

func (z ranFeedLikeDo) FirstOrCreate() (*model.RanFeedLike, error) {
	if result, err := z.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RanFeedLike), nil
	}
}

func (z ranFeedLikeDo) FindByPage(offset int, limit int) (result []*model.RanFeedLike, count int64, err error) {
	result, err = z.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = z.Offset(-1).Limit(-1).Count()
	return
}

func (z ranFeedLikeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = z.Count()
	if err != nil {
		return
	}

	err = z.Offset(offset).Limit(limit).Scan(result)
	return
}

func (z ranFeedLikeDo) Scan(result interface{}) (err error) {
	return z.DO.Scan(result)
}

func (z ranFeedLikeDo) Delete(models ...*model.RanFeedLike) (result gen.ResultInfo, err error) {
	return z.DO.Delete(models)
}

func (z *ranFeedLikeDo) withDO(do gen.Dao) *ranFeedLikeDo {
	z.DO = *do.(*gen.DO)
	return z
}
