input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["filebeat-logs"]
    group_id => "logstash-filebeat"
    auto_offset_reset => "latest"
    consumer_threads => 1
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "filebeat-%{+YYYY.MM.dd}"
  }
}
